<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/inspection" class="list-group-item">
          <h4 class="list-group-item-heading">Fiscalização Rotineira</h4>
        </a>
        <a href="/inspection/new" class="list-group-item">Cadastro</a>
        <a href="/inspection/view" class="list-group-item active">Pesquisa</a>
      </div>
      <div class="list-group">
        <a href="/clandestine" class="list-group-item">
          <h4 class="list-group-item-heading">Transporte Clandestino</h4>
        </a>
        <a href="/clandestine/new" class="list-group-item">Cadastro</a>
        <a href="/clandestine/view" class="list-group-item">Pesquisa</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/inspection">Fiscalização</a></li>
        <li class="active">Pesquisar</li>
      </ol>  
      <div class="page-header">
        <h1>Pesquisa <small>gerencie aqui os dados das fiscalizações</small></h1>
        <hr>
        <form class="form-search" action="/inspection/view" method="get">
          <div class="form-group col-md-4">
            <input type="text" class="form-control search-query" placeholder="pesquisa" name="field" value="<?=$this->field?>">
          </div>
          <div class="form-group col-md-3">
            <select name="optionSearch" class="form-control">
              <option value="0">Pesquisar por:</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Pesquisar</button>
        </form>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Local</th>
            <th>Permissionário</th>
            <th>Data</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $inspection){?>
                <tr>
                  <td><a href="/inspection/edit/id/<?=$inspection->inspection_id?>"><?=$inspection->local?></a></td>
                  <td><?=$inspection->name?></td>
                  <td><?=$inspection->inspection_date?></td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhuma fiscalização na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>