<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li><a href="/assessment/new">Cadastro</a></li>
          <li><a href="/assessment/view">Pesquisa</a></li>
          <li><a href="/assessment/report">Relatórios</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
      <div class="well">
        <img class="img-polaroid" src="/img/autuacao.jpg"><br><br>
        <h1>Autuação</h1>
        <p>Descrição de Autuação </p>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>