<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="active"><a href="/assessment/new">Cadastro</a></li>
          <li><a href="/assessment/view">Pesquisa</a></li>
          <li><a href="/assessment/report">Relatórios</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
    		<h1>Nova Autuação <small>defina aqui os dados da autuação</small></h1>
        <hr>
        <?=$this->form?>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>