<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li><a href="/assessment/new">Cadastro</a></li>
          <li class="active"><a href="/assessment/view">Pesquisa</a></li>
          <li><a href="/assessment/report">Relatórios</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
    </div><!--/span-->
  </div><!--/row-->
</div>