<div class="masthead">
  <h3 class="muted">SETOP</h3>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">
          <li class="active"><a href="#">Taxi</a></li>
          <li><a href="http://www.sgtm.mg.gov.br">SGTM</a></li>
          <li><a href="http://www.sgti.setop.mg.gov.br">SGTI</a></li>
        </ul>
      </div>
    </div>
  </div><!-- /.navbar -->
</div>

  <!-- Jumbotron -->
  <div class="jumbotron">
    <h1>Sistema de Controle de Táxi</h1>
    <p class="lead">Um sistema de gestão de taxis metropolitanos, de acordo com a lei 15.775/2005.</p>
    <a class="btn btn-large btn-success" href="/auth/login">Entrar</a>
  </div>

  <hr>