<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="#"><i class="icon-user"></i> Permissionários </a></li>
        <li><a href="#"><i class="icon-bullhorn"></i> Auxiliares </a></li>
        <li><a href="#"><i class="icon-map-marker"></i> Veículos e Taxímetros </a></li>
        <li><a href="#"><i class="icon-picture"></i> Consultas </a></li>
        <li><a href="#"><i class="icon-wrench"></i> Guias de Recolhimento </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	teste
      </div>
    </div>
  </div>
</div>