<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/account/personal"><i class="icon-user"></i> Pessoais </a></li>
        <li><a href="/account/photo"><i class="icon-picture"></i> Foto </a></li>
        <li><a href="/account/password"><i class="icon-wrench"></i> Senha </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="well">
      	<h1>Configurações <small>deixe seu perfil atualizado</small></h1>
      	<div>
      		Aqui é possível alterar seus dados pessoais, contatos e sua senha. 
      	</div>
      </div>
    </div>
  </div>
</div>