<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/account" class="list-group-item">
          <h4 class="list-group-item-heading">Conta</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da sua conta</p>
        </a>
        <a href="/account/personal" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Pessoais</a>
        <a href="/account/photo" class="list-group-item"><span class="glyphicon glyphicon-picture"></span> Foto</a>
        <a href="/account/password" class="list-group-item"><span class="glyphicon glyphicon-wrench"></span> Senha</a>
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li class="active">Conta</li>
      </ol>  
      <div class="well">
      	<h1>Configurações <small>deixe seu perfil atualizado</small></h1>
      	<div>
      		Aqui é possível alterar seus dados pessoais, contatos e sua senha. 
      	</div>
      </div>
    </div>
  </div>
</div>