<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/account/access"><i class="icon-user"></i> Acesso </a></li>
        <li><a href="/account/personal"><i class="icon-bullhorn"></i> Pessoais </a></li>
        <li><a href="/account/photo"><i class="icon-picture"></i> Foto </a></li>
        <li><a href="/account/password"><i class="icon-wrench"></i> Senha </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Configurações <small>deixe seu perfil sempre atualizado</small></h1>
      </div>
    </div>
  </div>
</div>