<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/account/access"><i class="icon-user"></i> Acesso </a></li>
        <li><a href="/account/personal"><i class="icon-bullhorn"></i> Pessoais </a></li>
        <li><a href="/account/photo"><i class="icon-picture"></i> Foto </a></li>
        <li class="active"><a href="/account/password"><i class="icon-wrench"></i> Senha </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Senha <small>defina aqui sua senha</small></h1>
				<hr>
				<form class="form-horizontal">
				<div class="control-group">
				    <label class="control-label" for="old_password">Senha atual</label>
				    <div class="controls">
				        <input type="password" name="old_password" value="" class="input-large" id="old_password" placeholder="senha atual">
				    </div><!--/.controls -->
				</div><!--/.control-group -->
				<div class="control-group">
				    <label class="control-label" for="password">Nova senha</label>
				    <div class="controls">
				        <input type="password" name="password" value="" class="input-large" id="password" placeholder="nova senha">
				    </div><!--/.controls -->
				</div><!--/.control-group -->
				<div class="control-group">
				    <label class="control-label" for="confirm_password">Confirme sua nova senha</label>
				    <div class="controls">
				        <input type="password" name="confirm_password" value="" class="input-large" id="confirm_password" placeholder="confirme sua nova senha">
				    </div><!--/.controls -->
				</div><!--/.control-group -->
				<div class="form-actions">
				    <button type="submit" class="btn btn-primary">Salvar alterações</button>
				</div>
				</form>
      </div>
    </div>
  </div>
</div>