<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/account/access"><i class="icon-user"></i> Acesso </a></li>
        <li class="active"><a href="/account/personal"><i class="icon-bullhorn"></i> Pessoais </a></li>
        <li><a href="/account/photo"><i class="icon-picture"></i> Foto </a></li>
        <li><a href="/account/password"><i class="icon-wrench"></i> Senha </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
    	<div class="page-header">
        <h1>Dados Pessoais <small>defina aqui seus contatos</small></h1>
        <hr>
        <form class="form-horizontal">
          <div class="control-group">
              <label class="control-label" for="name">Telefone</label>
              <div class="controls">
                  <input type="text" name="phone" value="" class="input-large" id="phone" placeholder="telefone">
              </div><!--/.controls -->
          </div><!--/.control-group -->
          <div class="control-group">
              <label class="control-label" for="email">Email</label>
              <div class="controls">
                  <input type="email" name="email" value="" class="input-large" id="email" placeholder="email">
              </div><!--/.controls -->
          </div><!--/.control-group -->
          <div class="form-actions">
              <button type="submit" class="btn btn-primary">Salvar alterações</button>
          </div>
        </form>
      </div>
      </div>
    </div>
  </div>
</div>