<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="active"><a href="/survey/calendar">Cronograma</a></li>
          <li><a href="#">Cadastro</a></li>
          <li><a href="#">Pesquisa</a></li>
          <li><a href="#">Relatórios</a></li>
          <li><a href="#">Visualização</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
    	<div class="page-header">
				<div class="pull-right form-inline">
					<div class="btn-group">
						<button class="btn btn-primary" data-calendar-nav="prev">&lt;&lt; Anterior</button>
						<button class="btn" data-calendar-nav="today">Hoje</button>
						<button class="btn btn-primary" data-calendar-nav="next">Próximo &gt;&gt;</button>
					</div>
					<div class="btn-group">
						<button class="btn btn-warning" data-calendar-view="year">Ano</button>
						<button class="btn btn-warning active" data-calendar-view="month">Mês</button>
						<button class="btn btn-warning" data-calendar-view="week">Semana</button>
						<button class="btn btn-warning" data-calendar-view="day">Dia</button>
					</div>
				</div>
			</div>
			<div id="calendar"></div>
    </div>
    </div><!--/span-->
  </div><!--/row-->
</div>