<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li><a href="#">Cronograma</a></li>
          <li><a href="#">Cadastro</a></li>
          <li><a href="#">Pesquisa</a></li>
          <li><a href="#">Relatórios</a></li>
          <li><a href="#">Visualização</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>