<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/survey" class="list-group-item">
          <h4 class="list-group-item-heading">Vistoria</h4>
        </a>
        <a href="#" class="list-group-item">Cronograma</a>
        <a href="#" class="list-group-item">Cadastro</a>
        <a href="#" class="list-group-item">Pesquisa</a>
        <a href="#" class="list-group-item">Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li class="active">Vistoria</li>
      </ol>  
      <div class="well">
        <img class="img-polaroid" src="/img/vistoria.jpg"><br><br>
        <h1>Vistoria</h1>
        <p>Descrição de Vistoria </p>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>