<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/auxiliar" class="list-group-item">
          <h4 class="list-group-item-heading">Auxiliares</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos auxiliares</p>
        </a>
        <a href="/auxiliar/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/auxiliar/new" class="list-group-item active">Edição</a>
        <a href="/auxiliar/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/auxiliar/report" class="list-group-item"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/auxiliar">Auxiliar</a></li>
        <li class="active">Edição</li>
      </ol>  
      <div class="page-header">
        <h1><?=$this->auxiliar->name?> <small>dados do auxiliar</small></h1>
        <hr>
        <div>
            <p>
              <a href="/auxiliar/print-data/id/<?=$this->auxiliar->id_auxiliar?>" class="btn btn-default help" data-toggle="tooltip" title="Imprimir dados"><i class="icon-file"></i></a>
              <a href="#license_<?=$this->auxiliar->id_auxiliar?>" class="btn btn-default help" data-toggle="modal" title="Imprimir a carteira"><i class="icon-print"></i></a>
            </p>
        </div>
        <hr>
        <ul class="nav nav-tabs" id="myTab">
          <li class="active"><a href="#data">Dados</a></li>
          <li><a href="#grantee">Permissionários</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="data"><br>
                <form class="form-horizontal" action="/auxiliar/edit/id/<?=$this->auxiliar->id_auxiliar?>" method="post">
                  <div class="panel-group" id="accordion1">
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a class="panel-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseMain">Dados Principais</a>
                          </h4>
                        </div>
                        <div id="collapseMain" class="panel-collapse collapse">
                          <div class="panel-body">
                            <div class="control-group">
                                <label class="control-label" for="name">Nome</label>
                                <div class="controls">
                                    <input type="text" name="name" value="<?=$this->auxiliar->name?>" class="input-xlarge" id="name" placeholder="nome completo">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="info">Observações</label>
                                <div class="controls">
                                    <textarea type="text" name="info" rows="5" class="input-xlarge" id="info" placeholder="observações"><?=$this->auxiliar->info?></textarea>
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                          </div>
                        </div>
                      </div>
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a class="panel-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseAddress">Endereço</a>
                          </h4>
                        </div>
                        <div id="collapseAddress" class="panel-collapse collapse">
                          <div class="panel-body">
                            <div class="control-group">
                                <label class="control-label" for="address">Endereço</label>
                                <div class="controls">
                                    <input type="text" name="address" value="<?=$this->auxiliar->address?>" class="input-xlarge" id="address" placeholder="logradouro">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="number">Número</label>
                                <div class="controls">
                                    <input type="text" name="number" value="<?=$this->auxiliar->number?>" class="input-xlarge" id="number" placeholder="número">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="apartament">Complemento</label>
                                <div class="controls">
                                    <input type="text" name="apartament" value="<?=$this->auxiliar->apartament?>" class="input-xlarge" id="apartament" placeholder="complemento">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="neighborhood">Bairro</label>
                                <div class="controls">
                                    <input type="text" name="neighborhood" value="<?=$this->auxiliar->neighborhood?>" class="input-xlarge" id="neighborhood" placeholder="bairro">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="address_city">Cidade</label>
                                <div class="controls">
                                  <select name="address_city" id="address_city" class="input-xlarge">
                                    <option value="0" <?if($this->auxiliar->address_city == 0) echo 'selected="selected"'; ?>>-- Escolha o município --</option>
                                    <?foreach ($this->cities as $city){ ?>
                                    <option <?if($this->auxiliar->address_city == $city->id) echo 'selected="selected"'; ?> value="<?=$city->id?>"><?=$city->name?></option>
                                    <?}?>
                                  </select>
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="zipcode">CEP</label>
                                <div class="controls">
                                    <input type="text" name="zipcode" value="<?=$this->auxiliar->zipcode?>" class="input-xlarge" id="zipcode" placeholder="cep" data-mask="99999-999">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                          </div>
                        </div>
                      </div>
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a class="panel-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseContact">Contato</a>
                          </h4>
                        </div>
                        <div id="collapseContact" class="panel-collapse collapse">
                          <div class="panel-body">
                            <div class="control-group">
                                <label class="control-label" for="phone">Telefone fixo</label>
                                <div class="controls">
                                    <input type="text" name="phone" value="<?=$this->auxiliar->phone?>" class="input-xlarge" id="phone" placeholder="telefone fixo" data-mask="(99) 9999-9999">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="mobile">Celular</label>
                                <div class="controls">
                                    <input type="text" name="mobile" value="<?=$this->auxiliar->mobile?>" class="input-xlarge" id="mobile" placeholder="celular" data-mask="(99) 9999-9999">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="email">Email</label>
                                <div class="controls">
                                    <input type="text" name="email" value="<?=$this->auxiliar->email?>" class="input-xlarge" id="email" placeholder="email">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                          </div>
                        </div>
                      </div>
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a class="panel-toggle" data-toggle="collapse" data-parent="#panel" href="#collapseDocument">Documentos</a>
                          </h4>
                        </div>
                        <div id="collapseDocument" class="panel-collapse collapse">
                          <div class="panel-body">
                            <div class="control-group">
                                <label class="control-label" for="rg">Identidade</label>
                                <div class="controls">
                                    <input type="text" name="rg" value="<?=$this->auxiliar->rg?>" class="input-xlarge" id="rg" placeholder="identidade">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="rg_issuer">Orgão Emissor da Identidade</label>
                                <div class="controls">
                                    <input type="text" name="rg_issuer" value="<?=$this->auxiliar->rg_issuer?>" class="input-xlarge" id="rg_issuer" placeholder="orgão emissor da identidade">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="cpf">CPF</label>
                                <div class="controls">
                                    <input type="text" name="cpf" value="<?=$this->auxiliar->cpf?>" class="input-xlarge" id="cpf" placeholder="cpf" data-mask="999.999.999-99">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="cnh">Habilitação</label>
                                <div class="controls">
                                    <input type="text" name="cnh" value="<?=$this->auxiliar->cnh?>" class="input-xlarge" id="cnh" placeholder="habilitação">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="cnh_issuer">Orgão Emissor da Habilitação</label>
                                <div class="controls">
                                    <input type="text" name="cnh_issuer" value="<?=$this->auxiliar->cnh_issuer?>" class="input-xlarge" id="cnh_issuer" placeholder="orgão emissor da habilitação">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="iapas">IAPAS</label>
                                <div class="controls">
                                    <input type="text" name="iapas" value="<?=$this->auxiliar->iapas?>" class="input-xlarge" id="iapas" placeholder="iapas">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="voter">Título de Eleitor</label>
                                <div class="controls">
                                    <input type="text" name="voter" value="<?=$this->auxiliar->voter?>" class="input-xlarge" id="voter" placeholder="título de eleitor">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="voter_zone">Zona Eleitoral</label>
                                <div class="controls">
                                    <input type="text" name="voter_zone" value="<?=$this->auxiliar->voter_zone?>" class="input-xlarge" id="voter_zone" placeholder="zona eleitoral">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="army">Militar</label>
                                <div class="controls">
                                    <input type="text" name="army" value="<?=$this->auxiliar->army?>" class="input-xlarge" id="army" placeholder="documento militar">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                            <div class="control-group">
                                <label class="control-label" for="army_issuer">Orgão Emissor Militar</label>
                                <div class="controls">
                                    <input type="text" name="army_issuer" value="<?=$this->auxiliar->army_issuer?>" class="input-xlarge" id="army_issuer" placeholder="orgão emissor do documento militar">
                                </div><!--/.controls -->
                            </div><!--/.control-group -->
                          </div>
                        </div>
                      </div>
                    </div><br>
                  <div class="form-group">
                    <div class="col-lg-5">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                      <a data-toggle="modal" href="#myModal" class="btn btn-danger">Remover auxiliar</a>
                    </div>
                  </div>
                </form>
            </div>
            <div class="tab-pane" id="grantee"><br>
              <form class="form-horizontal" method="post" action="/auxiliar/save-grantee">
                  <table class="table table-hover table-bordered" id='tableGrantees'>
                    <thead>
                        <th>&nbsp;</th>
                        <th>Nome</th>
                        <th>Permissão</th>
                        <th>Início</th>
                        <th>Fim</th>
                    </thead>
                    <tbody>
                        <?foreach($this->historicGrantees as $historicGrantees){?>
                        <tr <?if($historicGrantees->end_date == '') echo 'class="success"'; else echo 'class="danger"';?>> 
                            <td>&nbsp;</td>
                            <td><?=$historicGrantees->name?></td>
                            <td><?=$historicGrantees->permission?> <input type="hidden" name="permission[]" value="<?=$historicGrantees->permission?>"> <input type="hidden" name="_id[]" value="<?=$historicGrantees->_id?>"></td>
                            <td><input type="text" class="form-control dateMask" name="start_date[]" value="<?=Application_Model_General::dateToBr($historicGrantees->start_date)?>"></td>
                            <td><input type="text" class="form-control dateMask" name="end_date[]" value="<?=Application_Model_General::dateToBr($historicGrantees->end_date)?>"></td>
                        </tr>
                        <?}?>
                        <tr>
                            <td colspan='5'>
                                <a style='color: grey;' id='addGranteeInAuxiliar' href='#'><i class="icon-plus-sign-alt icon-large"></i></a>
                            </td>
                        </tr>
                    </tbody>
                  </table>
                  <div>
                    <input type="submit" class="btn btn-primary" value="Salvar">
                    <input type="hidden" name="auxiliar_add" value="<?=$this->auxiliar->id_auxiliar?>">
                  <div>
              </form>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="license_<?=$this->auxiliar->id_auxiliar?>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Emissão de Carteira</h3>
      </div>
      <form class="form-horizontal" action="/auxiliar/print-license/id/<?=$this->auxiliar->id_auxiliar?>" method="post">
        <div class="modal-body">
            <div class="form-group">
              <label class="col-lg-4 control-label" for="end_date">Data de Vencimento</label>
              <div class="col-lg-5">
                <input type="text" class="form-control dateMask" id="end_date" name="end_date" placeholder="data de vencimento">
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Fechar</button>
          <input type="submit" class="btn btn-primary" value="Emitir">
        </div>
      </form>
    </div>
  </div>
</div>

<form action="/auxiliar/remove/id/<?=$this->auxiliar->id_auxiliar?>" method="post">
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Remover auxiliar</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja remover o auxiliar <?=$this->auxiliar->name?>?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-danger">Remover</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>