<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/auxiliar" class="list-group-item">
          <h4 class="list-group-item-heading">Auxiliares</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos auxiliares</p>
        </a>
        <a href="/auxiliar/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/auxiliar/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/auxiliar/report" class="list-group-item"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li class="active">Auxiliar</li>
      </ol>  
      <div class="well">
        <img class="img-responsive img-thumbnail" src="/img/taxi_auxiliar.jpg"><br><br>
        <h1>Auxiliar</h1>
        <p>O serviço público de transporte individual de passageiros por táxi especial metropolitano poderá ser prestado por terceiros mediante permissão, obtida por meio de licitação, respeitada a legislação vigente.</p>
      </div>
    </div>
    </div>
  </div>
</div>