<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/auxiliar/new"><i class="icon-user"></i> Novo Auxiliar </a></li>
        <li><a href="/auxiliar/view"><i class="icon-bullhorn"></i> Pesquisar Auxiliares </a></li>
        <li><a href="/auxiliar/report"><i class="icon-map-marker"></i> Relatórios </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="well">
        <img class="img-polaroid" src="/img/taxi_auxiliar.jpg"><br><br>
        <h1>Auxiliar</h1>
        <p>O serviço público de transporte individual de passageiros por táxi especial metropolitano poderá ser prestado por terceiros mediante permissão, obtida por meio de licitação, respeitada a legislação vigente.</p>
      </div>
    </div>
    </div>
  </div>
</div>