<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="#"><i class="icon-user"></i> Novo Auxiliar </a></li>
        <li><a href="#"><i class="icon-bullhorn"></i> Visualizar Auxiliares </a></li>
        <li><a href="#"><i class="icon-map-marker"></i> Relatórios </a></li>
        <li><a href="#"><i class="icon-picture"></i> Emissão de Carteiras </a></li>
        <li><a href="#"><i class="icon-wrench"></i> Guias de Recolhimento </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="well">
      	<h1>Auxiliares</h1>
      </div>
    </div>
  </div>
</div>