<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li class="active"><a href="/auxiliar/new"><i class="icon-user"></i> Novo Auxiliar </a></li>
        <li><a href="/auxiliar/view"><i class="icon-bullhorn"></i> Pesquisar Auxiliares </a></li>
        <li><a href="/auxiliar/report"><i class="icon-map-marker"></i> Relatórios </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
        <h1>Novo Auxiliar <small>defina aqui os dados do auxiliar</small></h1>
        <hr>
        <form class="form-horizontal" action="/auxiliar/new" method="post">
          <div class="control-group">
            <div class="accordion" id="acoordion1">
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseMain">Dados Principais</a>
                </div>
                <div id="collapseMain" class="accordion-body collapse in">
                  <div class="accordion-inner">
                    <div class="control-group">
                        <label class="control-label" for="name">Nome</label>
                        <div class="controls">
                            <input type="text" name="name" value="" class="input-xlarge" id="name" placeholder="nome completo">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="city">Cidade</label>
                        <div class="controls">
                          <select name="city" id="city" class="input-xlarge">
                            <option value="0">-- Escolha o município --</option>
                            <option value="1">Belo Horizonte</option>
                            <option value="2">Sete Lagoas</option>
                            <option value="3">Contagem</option>
                            <option value="4">Betim</option>
                            <option value="5">Santa Luzia</option>
                            <option value="6">Sabará</option>
                            <option value="7">Caeté</option>
                            <option value="8">Confins</option>
                            <option value="9">Ibirité</option>
                            <option value="10">Nova Lima</option>
                            <option value="11">Rio Acima</option>
                            <option value="12">Ribeirão das Neves</option>
                            <option value="13">Raposos</option>
                            <option value="14">Vespasiano</option>
                            <option value="15">Pedro Leopoldo</option>
                          </select>
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="info">Observações</label>
                        <div class="controls">
                            <textarea type="text" name="info" rows="5" class="input-xlarge" id="info" placeholder="observações"></textarea>
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseAddress">Endereço</a>
                </div>
                <div id="collapseAddress" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <div class="control-group">
                        <label class="control-label" for="address">Endereço</label>
                        <div class="controls">
                            <input type="text" name="address" value="" class="input-xlarge" id="address" placeholder="logradouro">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="number">Número</label>
                        <div class="controls">
                            <input type="text" name="number" value="" class="input-xlarge" id="number" placeholder="número">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="apartament">Complemento</label>
                        <div class="controls">
                            <input type="text" name="apartament" value="" class="input-xlarge" id="apartament" placeholder="complemento">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="neighborhood">Bairro</label>
                        <div class="controls">
                            <input type="text" name="neighborhood" value="" class="input-xlarge" id="neighborhood" placeholder="bairro">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="address_city">Cidade</label>
                        <div class="controls">
                            <select name="address_city" id="address_city" class="input-xlarge">
                              <option value="0">-- Escolha o município --</option>
                              <option value="1">Belo Horizonte</option>
                              <option value="2">Sete Lagoas</option>
                              <option value="3">Contagem</option>
                              <option value="4">Betim</option>
                              <option value="5">Santa Luzia</option>
                              <option value="6">Sabará</option>
                              <option value="7">Caeté</option>
                              <option value="8">Confins</option>
                              <option value="9">Ibirité</option>
                              <option value="10">Nova Lima</option>
                              <option value="11">Rio Acima</option>
                              <option value="12">Ribeirão das Neves</option>
                              <option value="13">Raposos</option>
                              <option value="14">Vespasiano</option>
                              <option value="15">Pedro Leopoldo</option>
                            </select>
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="zipcode">CEP</label>
                        <div class="controls">
                            <input type="text" name="zipcode" value="" class="input-xlarge" id="zipcode" placeholder="cep">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseContact">Contato</a>
                </div>
                <div id="collapseContact" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <div class="control-group">
                        <label class="control-label" for="phone">Telefone fixo</label>
                        <div class="controls">
                            <input type="text" name="phone" value="" class="input-xlarge" id="phone" placeholder="telefone fixo" data-mask="(99) 9999-9999">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="mobile">Celular</label>
                        <div class="controls">
                            <input type="text" name="mobile" value="" class="input-xlarge" id="mobile" placeholder="celular" data-mask="(99) 9999-9999">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="email">Email</label>
                        <div class="controls">
                            <input type="text" name="email" value="" class="input-xlarge" id="email" placeholder="email">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseDocument">Documentos</a>
                </div>
                <div id="collapseDocument" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <div class="control-group">
                        <label class="control-label" for="rg">Identidade</label>
                        <div class="controls">
                            <input type="text" name="rg" value="" class="input-xlarge" id="rg" placeholder="identidade">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="rg_issuer">Orgão Emissor da Identidade</label>
                        <div class="controls">
                            <input type="text" name="rg_issuer" value="" class="input-xlarge" id="rg_issuer" placeholder="orgão emissor da identidade">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="cpf">CPF</label>
                        <div class="controls">
                            <input type="text" name="cpf" value="" class="input-xlarge" id="cpf" placeholder="cpf" data-mask="999.999.999-99">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="cnh">Habilitação</label>
                        <div class="controls">
                            <input type="text" name="cnh" value="" class="input-xlarge" id="cnh" placeholder="habilitação">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="cnh_issuer">Orgão Emissor da Habilitação</label>
                        <div class="controls">
                            <input type="text" name="cnh_issuer" value="" class="input-xlarge" id="cnh_issuer" placeholder="orgão emissor da habilitação">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="iapas">IAPAS</label>
                        <div class="controls">
                            <input type="text" name="iapas" value="" class="input-xlarge" id="iapas" placeholder="iapas">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="voter">Título de Eleitor</label>
                        <div class="controls">
                            <input type="text" name="voter" value="" class="input-xlarge" id="voter" placeholder="título de eleitor">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="voter_zone">Zona Eleitoral</label>
                        <div class="controls">
                            <input type="text" name="voter_zone" value="" class="input-xlarge" id="voter_zone" placeholder="zona eleitoral">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="army">Militar</label>
                        <div class="controls">
                            <input type="text" name="army" value="" class="input-xlarge" id="army" placeholder="documento militar">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                    <div class="control-group">
                        <label class="control-label" for="army_issuer">Orgão Emissor Militar</label>
                        <div class="controls">
                            <input type="text" name="army_issuer" value="" class="input-xlarge" id="army_issuer" placeholder="orgão emissor do documento militar">
                        </div><!--/.controls -->
                    </div><!--/.control-group -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
              <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>