<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/auxiliar" class="list-group-item">
          <h4 class="list-group-item-heading">Auxiliares</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos auxiliares</p>
        </a>
        <a href="/auxiliar/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/auxiliar/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/auxiliar/report" class="list-group-item active"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <div class="well">
      	<h1>Auxiliares</h1>
      </div>
    </div>
  </div>
</div>