<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/auxiliar" class="list-group-item">
          <h4 class="list-group-item-heading">Auxiliares</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos auxiliares</p>
        </a>
        <a href="/auxiliar/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/auxiliar/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/auxiliar/report" class="list-group-item active"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/grantee">Auxiliares</a></li>
        <li class="active">Relatórios</li>
      </ol> 
      <div class="col-lg-4"> <!--Lista Completa-->
        <h2>Lista Completa</h2>
          <p>Lista completa dos auxiliares com seus principais dados.</p>
          <form class="form-inline" action="/auxiliar/report-auxiliar-all" method="get" role="form">
              <select name="optionCity" class="form-control">
                <?foreach($this->cities as $cityOptions)
                {?>
                  <option value="<?=$cityOptions['id']?>"><?if($cityOptions['name'] == ""){?>--- TODAS AS CIDADES ---</option>
                    <?}else{
                      echo $cityOptions['name']?></option>
                    <?}
                }?>
              </select>
              <button type="submit" id='aux_all_pdf' name='aux_all' class="btn btn-primary" value="0">Gerar Pdf</button>
              <button type="submit" id='aux_all_csv' name='aux_all' class="btn btn-primary" value="1">Gerar Csv</button>
          </form>
        </div>
        <div class="col-lg-4">
        <h2>Lista Ativos</h2> <!--Lista Ativos-->
          <p>Lista completa dos auxiliares ativos no sistema.</p>
          <form class="form-inline" action="/auxiliar/report-auxiliar-active-all" method="get" role="form">
              <select name="optionCity" class="form-control">
                <?foreach($this->cities as $cityOptions)
                {?>
                  <option value="<?=$cityOptions['id']?>"><?if($cityOptions['name'] == ""){?>--- TODAS AS CIDADES ---</option>
                    <?}else{
                      echo $cityOptions['name']?></option>
                    <?}
                }?>
              </select>
              <button type="submit" id='aux_all_pdf' name='aux_all' class="btn btn-primary" value="0">Gerar Pdf</button>
              <button type="submit" id='aux_all_csv' name='aux_all' class="btn btn-primary" value="1">Gerar Csv</button>
          </form>
        </div>
        <div class="col-lg-4">
          <h2>Permissionarios e Auxiliares Ativos</h2> <!--Lista de Permissionariois e Auxiliars Ativos-->
          <p>Número de Permissionarios e Auxiliares ativos no sistema.</p>
          <form class="form-inline" action="/auxiliar/report-grantee-auxiliar-active-all" method="get" role="form">
              <select name="optionCity" class="form-control">
                <?foreach($this->cities as $cityOptions)
                {?>
                  <option value="<?=$cityOptions['id']?>"><?if($cityOptions['name'] == ""){?>--- TODAS AS CIDADES ---</option>
                    <?}else{
                      echo $cityOptions['name']?></option>
                    <?}
                }?>
              <input type="text" name="data_crt" placeholder="Digite a data de corte">
              </select>
              <p></p>
              <button type="submit" id='aux_all_pdf' name='aux_all' class="btn btn-primary" value="0">Gerar Pdf</button>
              <button type="submit" id='aux_all_csv' name='aux_all' class="btn btn-primary" value="1">Gerar Csv</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>