<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/auxiliar/new"><i class="icon-user"></i> Novo Auxiliar </a></li>
        <li><a href="/auxiliar/view"><i class="icon-bullhorn"></i> Pesquisar Auxiliares </a></li>
        <li class="active"><a href="/auxiliar/report"><i class="icon-map-marker"></i> Relatórios </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="well">
      	<h1>Auxiliares</h1>
      </div>
    </div>
  </div>
</div>