<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/auxiliar" class="list-group-item">
          <h4 class="list-group-item-heading">Auxiliares</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos auxiliares</p>
        </a>
        <a href="/auxiliar/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/auxiliar/view" class="list-group-item active"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/auxiliar/report" class="list-group-item"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/auxiliar">Auxiliar</a></li>
        <li class="active">Pesquisa</li>
      </ol>  
      <div class="page-header">
        <h1>Pesquisa <small>gerencie aqui os dados do auxiliar</small></h1>
        <hr>
        <form class="form-inline" action="/auxiliar/view" method="get">
          <div class="form-group col-md-4">
            <input type="text" class="form-control search-query" placeholder="pesquisa" name="field" value="<?=$this->field?>">
          </div>
          <div class="form-group col-md-3">
            <select name="optionSearch" class="form-control">
              <option value="0">Pesquisar por:</option>
              <option value="2" <?if($this->optionSearch == 2) echo "selected='selected'"; ?>>CPF</option>
              <option value="3" <?if($this->optionSearch == 3) echo "selected='selected'"; ?>>Nome</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Pesquisar</button>
        </form>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Nome</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $auxiliar){?>
                <tr>
                  <td><a href="/auxiliar/edit/id/<?=$auxiliar->id?>"><?=$auxiliar->name?></a></td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não encontrado nenhum auxiliar na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>

<?if(is_object($this->list) && !isset($this->list->name)){
  foreach($this->list as $auxiliar){?>
<div id="license_<?=$auxiliar->id?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Emissão de Carteira</h3>
  </div>
  <form class="form-horizontal" action="/auxiliar/print-license/id/<?=$auxiliar->id?>" method="post">
    <div class="modal-body">
        <div class="control-group">
          <label class="control-label" for="end_date">Data de Vencimento</label>
          <div class="controls">
            <input type="text" class="input-xlarge dateMask" id="end_date" name="end_date" placeholder="data de vencimento">
          </div>
        </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
      <input type="submit" class="btn btn-primary" value="Salvar">
    </div>
  </form>
</div>
<? } }?>