<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/auxiliar/new"><i class="icon-user"></i> Novo Auxiliar </a></li>
        <li class="active"><a href="/auxiliar/view"><i class="icon-bullhorn"></i> Pesquisar Auxiliares </a></li>
        <li><a href="/auxiliar/report"><i class="icon-map-marker"></i> Relatórios </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
        <h1>Pesquisa <small>gerencie aqui os dados do permissionário</small></h1>
        <form class="form-search" action="/auxiliar/view" method="get">
          <input type="text" class="input-xlarge search-query" placeholder="pesquisa" name="field" value="<?=$this->field?>">
          <select name="optionSearch">
            <option value="0">Pesquisar por:</option>
            <option value="2" <?if($this->optionSearch == 2) echo "selected='selected'"; ?>>CPF</option>
            <option value="3" <?if($this->optionSearch == 3) echo "selected='selected'"; ?>>Nome</option>
          </select>
          <button type="submit" class="btn">Pesquisar</button>
        </form>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Nome</th>
            <th>&nbsp;</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $auxiliar){?>
                <tr>
                  <td><a href="/auxiliar/edit/id/<?=$auxiliar->id?>"><?=$auxiliar->name?></a></td>
                  <td><a href="/auxiliar/edit/id/<?=$auxiliar->id?>" class="editauxiliar" data-toggle="tooltip" title="Editar permissionário"><i class="icon-pencil"></i></a></td>
                  <!-- <td><a href="/auxiliar/print-data/id/<?=$auxiliar->id?>" class="printDataauxiliar" data-toggle="tooltip" title="Imprimir dados"><i class="icon-file"></i></a></td>
                  <td><a href="/auxiliar/print-license/id/<?=$auxiliar->id?>" class="printLicenseauxiliar" data-toggle="tooltip" title="Imprimir a carteira"><i class="icon-print"></i></a></td> -->
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não encontrado nenhum auxiliar na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>