
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Um sistema de gestão do transporte metropolitano">
    <meta name="author" content="SETOP">

    <title>SETOP | Táxi Metropolitano</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/lib/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/lib/datepicker.css" rel="stylesheet">
    <link href="/css/lib/jquery.realperson.css" rel="stylesheet"> 
    <link href="/css/scheduling.css" rel="stylesheet"> 

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/lib/html5shiv.js"></script>
      <script src="/js/lib/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
			<br>
      	<?if($this->save == 'success'){?>
		      <div class="row">
		        <div class="col-md-12 text-center alert alert-success fade in">
		          <button type="button" class="close" data-dismiss="alert">×</button>
		          <strong>Ok!</strong> Dados atualizados com sucesso.
		        </div>
		      </div>
		      <?}?>
		      <?if($this->save == 'failed'){?>
		      <div class="row">
		        <div class="col-md-12 text-center alert alert-danger fade in">
		          <button type="button" class="close" data-dismiss="alert">×</button>
		          <strong>Ops!</strong> Houve algum erro na inserção dos dados. Tente novamente ou contacte a SETOP.
		        </div>
		      </div>
	      <?}?>

      	<div class="page-header">
          <h1>Consulta de Agendamento</h1>
        </div>
        <br>
        <div class="row">
      	 	<div class="col-md-12 col-md-offset-3">
	      		<form class="form-horizontal" role="form" method="post" action="/agendamento/consulta">
		  				<div class="form-group">
		    				<label class="col-sm-2 control-label">Seu CPF:</label>
		  					<div class="col-sm-4">
		  						<input type="text" name="cpf" id="cpf" class="form-control cpf" placeholder="seu cpf" value="<?=$this->cpf?>">
		  					</div>
		  				</div>
						 	<div class="form-group">
						    <div class="col-sm-5">
						      <button type="submit" class="btn btn-default btn-primary">Consultar</button>
						    </div>
						  </div>
		        </div>
		      </form>
	    	</div>

	    	<? if(count($this->schedulings)){?>
	    	<div>
		    		<table class="table table-hover table-bordered text-left">
		      		<thead>
		      			<th>Nome</th>
		      			<th>Data</th>
		      			<th>Hora</th>
		      			<th>Ações</th>
		      		</thead>
		      		<tbody>
	      				<?foreach($this->schedulings as $schedulings){?>
	      				<tr>
	      					<td><?=$schedulings->name?></td>
	      					<td><?=Application_Model_General::dateToBr($schedulings->date)?></td>
	      					<td><?=$schedulings->str_hour?></td>
	      					<td width="290"> 
	      						<a class="btn btn-default" href="/agendamento/print-confirmation/id/<?=base64_encode($schedulings->id)?>">Imprimir</a>
	      						<button class="btn btn-default" onclick="fncReschedule(<?=$schedulings->id?>)">Reagendar</button> 
	      					 	<a class="btn btn-default" href="#removeScheduling_<?=$schedulings->id?>" data-toggle="modal">Cancelar</a>  
	      					</td>
	      				</tr>
	      				<?}?>
	      			</tbody>
	      		</table>
	    	</div>
	    	<?}elseif(isset($this->cpf)){?>
	    	<h3>Não há agendamentos com este CPF.</h3>
	    	<?}?>


		    <div class="row hide" id="reschedule">
		    	<div class="col-md-4">
			      <div>
			      	<div id="calendar">
		            <div></div>
		          </div>
		        </div>
		      </div>
		      <div class="col-md-8">
		    		<form class="form-horizontal hide" role="form" method="post" id="formSchedule" action="/scheduling/reschedule">
		    			<div class="form-group">
		    				<label class="col-sm-2 control-label">Horário</label>
		  					<div class="col-sm-10">
		      				<select class="form-control text-center" name="hour" id="hour">
		      					<option value="0">-- Escolha um horário --</option>
		      					<?foreach($this->hour as $hour){?>
		      					<option value="<?=$hour->id?>"><?=$hour->hour?></option>
		      					<?}?>
		      				</select>
		    				</div>
		    			</div>
						 	<div class="form-group">
						    <div class="col-sm-offset-2 col-sm-10">
						      <button type="submit" id='btnSchedule' class="btn btn-default btn-primary">Reagendar</button>
		              <input type="hidden" name="date" id="date" value="<?=date('Y-m-d')?>">
		              <input type="hidden" name="id" id="id" value="">
						    </div>
						  </div>
		    		</form>
		    	</div>
		    </div>

      </div>



    </div>



    <div id="footer">
      <div class="container">
        <p class="text-muted">Secretaria de Transportes e Obras Públicas | Governo de Minas</p>
      </div>
    </div>


	<?if(count($this->schedulings)){foreach($this->schedulings as $schedulings){ ?>
		<div id="removeScheduling_<?=$schedulings->id?>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				    <h3 id="myModalLabel">Cancelar agendamento</h3>
				  </div>
				  <form class="form-horizontal" action="/scheduling/remove" method="post">
				    <div class="modal-body">
				        <p>Tem certeza que deseja cancelar seu agendamento?</p>
				    </div>
				    <div class="modal-footer">
				      <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Fechar</button>
				      <input type="submit" class="btn btn-danger" value="Confirmar Cancelamento">
				      <input type="hidden" value="<?=base64_encode($schedulings->id)?>" name="id">
				    </div>
				  </form>
				</div>
			</div>
		</div>
	<?}}?>


    <script src="/js/lib/jquery-1.10.1.min.js" type="text/javascript"></script>
    <script src="/js/lib/jquery.maskedinput.min.js" type="text/javascript"></script>
    <script src="/js/lib/bootstrap.min.js" type="text/javascript"></script>
    <script src="/js/lib/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="/js/lib/jquery.realperson.min.js" type="text/javascript"></script>
    <script src="/js/schedule.js" type="text/javascript"></script>
  </body>
</html>
