
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Um sistema de gestão do transporte metropolitano">
    <meta name="author" content="SETOP">

    <title>SETOP | Táxi Metropolitano</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/lib/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/scheduling.css" rel="stylesheet"> 

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/lib/html5shiv.js"></script>
      <script src="/js/lib/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
      
    	 	<div class="page-header">
          <h1>Lista de procedimentos e documentação</h1>
        </div>

        <table class="table table-bordered table-hover">
        	<thead>
        		<th width="250">Procedimento</th>
        		<th>Documentos</th>
        	</thead>
        	<tr>
        		<td>Prova</td>
        		<td>
        			<li>Solicitação do permissionário</li> 
        			<li>Cópia de CNH</li>
        		</td>
        	</tr>
        	<tr>
        		<td>Cadastro de auxiliar</td>
        		<td>
        			<li>Pagamento da taxa</li> 
        			<li>Solicitação do cadastro feito pelo permissionário devidamento protocolado</li> 
        			<li>03 fotos 3x4 (recente/originais)</li>
        			<li>Atestado médico de sanidade física e mental (15 dias contados da data de expedição)</li> 
        			<li>Atestado de bons antecedentes</li>
        			<li>Certidões negativas dos registros de distruição criminal fornecidas pela justiça</li>
        			<li>Xerox e original do CPF</li>
        			<li>Xerox e original da carteira de identidade</li>
        			<li>Xerox e original da carteira nacional de habilitação</li>
        			<li>Xerox e original da prova de quitação militar (para homens)</li>
        			<li>Xerox e original do título de eleitor e comprovante de votação (2 turnos)</li>
        			<li>Xerox e original do comprovante de inscrição no INSS (como autônomo)</li>
        			<li>Xerox e original do comprovante pagamento do INSS</li>
        			<li>Xerox e original do comprovante de residência (água, luz ou telefone)</li>
        			<li>Xerox e original do curso SEST/SENAT (frente e verso)</li>
        			<li>Xerox do curso de treinamento do regulamento de táxi</li>
        		</td>
        	</tr>
        	<tr>
        		<td>Baixa de auxiliar</td>
        		<td>
        			<li>Pagamento da taxa</li> 
        			<li>Certificado de condutor</li>
        		</td>
        	</tr>
        	<tr>
        		<td>Reserva de permissão</td>
        		<td>
        			<li>Pagamento da taxa</li> 
        			<li>Certificado de condutor do permissionário</li>
        			<li>Certificado de condutor dos auxiliares</li> 
        			<li>Autorização de trafego</li>  
        		</td>
        	</tr>
        	<tr>
        		<td>Conclusão do emplacamento</td>
        		<td>
        			<li>Cópia da baixa de taxímetro</li> 
        			<li>Cópia do CRV no nome do permissionário</li> 
        			<li>Laudo de descaracterização do veículo que saiu do sistema</li> 
        			<li>Laudo de vistoria do veículo novo (emitido pelo DER/MG)</li> 
        			<li>Nota fiscal do veículo a ser emplacado</li> 
        		</td>
        	</tr>
        	<tr>
        		<td>Fazer carteira</td>
        		<td>        			
        			<li>Cópia da colocação do taxímetro</li> 
        			<li>Cópia do CRV como aluguel</li>
        			<li>Laudo do rastreador</li>  
        		</td>
        	</tr>
        	<tr>
        		<td>Solicitação de certidão</td>
        		<td>
        			<li>Solicitação antecipada</li> 
        		</td>
        	</tr>
        	<tr>
        		<td>Entrega de certidão</td>
        		<td>
        			<li>Pagamento de taxa</li> 
        			<li>Entregue <b>SOMENTE</b> ao solicitante</li> 
        		</td>
        	</tr>
        	<tr>
        		<td>Permuta de veículos</td>
        		<td>
        			<li>Interessados devem estar presentes</li> 
        			<li>Apresentar DUT devidamente preenchido e reconhecido firma</li> 
        			<li>Laudo de vistoria dos dois veículos(emitida pelo DER/MG)</li> 
        			<li>Certificados de condutor dos permissionários e auxiliares</li> 
        			<li>Autorização de trafego de ambos</li> 
        		</td>
        	</tr>
        	<tr>
        		<td>Segunda via de documentos</td>
        		<td>
        			<li>Solicitar antes</li> 
        		</td>
        	</tr>
        	<tr>
        		<td>Transferência de permissão</td>
        		<td>
        			<li>Consultar procedimentos</li> 
        		</td>
        	</tr>
        </table>
      </div>


    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted">Secretaria de Transportes e Obras Públicas | Governo de Minas</p>
      </div>
    </div>

  </body>
</html>