
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Usuários</li>
              <li><a href="/administration/user-new">Novo</a></li>
              <li><a href="/administration/user">Pesquisar</a></li>
              <li class="nav-header">Cidades</li>
              <li><a href="/administration/city-new">Novo</a></li>
              <li><a href="/administration/city">Pesquisar</a></li>
              <li class="nav-header">Modelos de Carro</li>
              <li><a href="/administration/model-vehicle-new">Novo</a></li>
              <li><a href="/administration/model-vehicle">Pesquisar</a></li>
              <li class="nav-header">Marcas de Carro</li>
              <li><a href="/administration/brand-vehicle-new">Novo</a></li>
              <li class="active"><a href="/administration/brand-vehicle">Pesquisar</a></li>
              <li class="nav-header">Modelos de Táximetro</li>
              <li><a href="/administration/model-taximeter-new">Novo</a></li>
              <li><a href="/administration/model-taximeter">Pesquisar</a></li>
              <li class="nav-header">Marcas de Táximetro</li>
              <li><a href="/administration/brand-taximeter-new">Novo</a></li>
              <li><a href="/administration/brand-taximeter">Pesquisar</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">   
         <div class="page-header">
            <h1>Pesquisa <small>gerencie aqui os dados dos modelos de carro</small></h1>
            <form class="form-search" action="/administration/brand-vehicle" method="get">
              <input type="text" class="input-xlarge search-query" placeholder="nome do usuário" name="field" value="<?=$this->field?>">
              <button type="submit" class="btn">Pesquisar</button>
            </form>
            <table class="table table-hover table-bordered">
              <thead>
                <th>Nome</th>
              </thead>
              <tbody>
                <?if(is_object($this->list) && !isset($this->list->name)){
                  foreach($this->list as $brandVehicle){?>
                    <tr>
                      <td><a href="/administration/brand-vehicle-edit/id/<?=$brandVehicle->id?>"><?=$brandVehicle->name?></a></td>
                    </tr>
                <?} } else{?>
                  <tr>
                    <td colspan="7">Não encontrado nenhum fiscal na pesquisa.</td>
                  </tr>
                <?}?>
              </tbody>
            </table>
            <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
          </div>
        </div><!--/span-->
      </div><!--/row-->