
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Usuários</li>
              <li><a href="/administration/user-new">Novo</a></li>
              <li><a href="/administration/user">Pesquisar</a></li>
              <li class="nav-header">Cidades</li>
              <li><a href="/administration/city-new">Novo</a></li>
              <li><a href="/administration/city">Pesquisar</a></li>
              <li class="nav-header">Modelos de Carro</li>
              <li><a href="/administration/model-vehicle-new">Novo</a></li>
              <li><a href="/administration/model-vehicle">Pesquisar</a></li>
              <li class="nav-header">Marcas de Carro</li>
              <li><a href="/administration/brand-vehicle-new">Novo</a></li>
              <li><a href="/administration/brand-vehicle">Pesquisar</a></li>
              <li class="nav-header">Modelos de Táximetro</li>
              <li><a href="/administration/model-taximeter-new">Novo</a></li>
              <li><a href="/administration/model-taximeter">Pesquisar</a></li>
              <li class="nav-header">Marcas de Táximetro</li>
              <li class="active"><a href="/administration/brand-taximeter-new">Novo</a></li>
              <li><a href="/administration/brand-taximeter">Pesquisar</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">   
          <div class="page-header">
            <h1>Marca de Taxímetro <small>defina aqui os dados do marca de taxímetro</small></h1>
            <hr>
            <?=$this->form?>
          </div>
        </div><!--/span-->
      </div><!--/row-->