
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Usuários</li>
              <li><a href="/administration/user-new">Novo</a></li>
              <li><a href="/administration/user">Pesquisar</a></li>
              <li><a href="#">Edição</a></li>
              <li class="nav-header">Cadastros</li>
              <li><a href="/administration/city">Cidades</a></li>
              <li class="active"><a href="#">Edição de cidade</a></li>
              <li><a href="#">Autorização</a></li>
              <li><a href="#">Combustível</a></li>
              <li class="nav-header">Carros</li>
              <li><a href="#">Marcas de Carro</a></li>
              <li><a href="#">Modelos de Carro</a></li>
              <li class="nav-header">Taxímetros</li>
              <li><a href="#">Marcas de Táximetro</a></li>
              <li><a href="#">Modelos de Táximetro</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">   
          <div class="page-header">
            <h1>Cidade <small>defina aqui os dados da cidade</small></h1>
            <hr>
            <?=$this->form?>
          </div>
        </div><!--/span-->
      </div><!--/row-->