<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
          <ul class="nav nav-list">
            <a href="/administration/user" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/city" class="list-group-item">
              <h4 class="list-group-item-heading">Cidades</h4>
            </a>
            <a href="/administration/city-new" class="list-group-item">Novo</a>
            <a href="/administration/city" class="list-group-item active">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/model-vehicle" class="list-group-item">
              <h4 class="list-group-item-heading">Modelos de Carro</h4>
            </a>
            <a href="/administration/model-vehicle-new" class="list-group-item">Novo</a>
            <a href="/administration/model-vehicle" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/brand-vehicle" class="list-group-item">
              <h4 class="list-group-item-heading">Marcas de Carro</h4>
            </a>
            <a href="/administration/brand-vehicle-new" class="list-group-item">Novo</a>
            <a href="/administration/brand-vehicle" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/model-taximeter" class="list-group-item">
              <h4 class="list-group-item-heading">Modelos de Taxímetro</h4>
            </a>
            <a href="/administration/model-taximeter-new" class="list-group-item">Novo</a>
            <a href="/administration/model-taximeter" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/brand-taximeter" class="list-group-item">
              <h4 class="list-group-item-heading">Marcas de Táximetro</h4>
            </a>
            <a href="/administration/brand-taximeter-new" class="list-group-item">Novo</a>
            <a href="/administration/brand-taximeter" class="list-group-item">Pesquisar</a>
          </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="col-md-9">
          <div class="page-header">
            <h1>Pesquisa <small>gerencie aqui os dados das cidades</small></h1>
            <hr>
            <form class="form-search" action="/administration/city" method="get">
              <div class="col-md-5">
                <input type="text" class="form-control search-query" placeholder="nome da cidade" name="field" value="<?=$this->field?>">
              </div>
              <button type="submit" class="btn btn-primary">Pesquisar</button>
            </form>
            <hr>
            <table class="table table-hover table-bordered">
              <thead>
                <th>Nome</th>
              </thead>
              <tbody>
                <?if(is_object($this->list) && !isset($this->list->name)){
                  foreach($this->list as $city){?>
                    <tr>
                      <td><a href="/administration/city-edit/id/<?=$city->id?>"><?=$city->name?></a></td>
                    </tr>
                <?} } else{?>
                  <tr>
                    <td colspan="7">Não encontrado nenhum fiscal na pesquisa.</td>
                  </tr>
                <?}?>
              </tbody>
            </table>
            <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
          </div>
        </div><!--/span-->
      </div><!--/row-->