
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <?if($this->institution == 1){?>
              <li class="nav-header">Usuários</li>
              <li><a href="/administration/user-new">Novo</a></li>
              <li><a href="/administration/user">Pesquisar</a></li>
              <li class="nav-header">Cidades</li>
              <li><a href="/administration/city-new">Novo</a></li>
              <li><a href="/administration/city">Pesquisa</a></li>
              <li class="nav-header">Modelos de Carro</li>
              <li><a href="/administration/model-vehicle-new">Novo</a></li>
              <li><a href="/administration/model-vehicle">Pesquisar</a></li>
              <li class="nav-header">Marcas de Carro</li>
              <li><a href="/administration/brand-vehicle-new">Novo</a></li>
              <li><a href="/administration/brand-vehicle">Pesquisar</a></li>
              <li class="nav-header">Modelos de Táximetro</li>
              <li><a href="/administration/model-taximeter-new">Novo</a></li>
              <li><a href="/administration/model-taximeter">Pesquisar</a></li>
              <li class="nav-header">Marcas de Táximetro</li>
              <li><a href="/administration/brand-taximeter-new">Novo</a></li>
              <li><a href="/administration/brand-taximeter">Pesquisar</a></li>
              <?}else if($this->institution == 2){?>
              <li class="nav-header">Fiscais</li>
              <li><a href="/administration/inspector-new">Cadastro</a></li>
              <li><a href="/administration/inspector">Pesquisa</a></li>
              <li class="nav-header">Fiscalização</li>
              <?}?>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1>Administração</h1>
            <p>Aqui você conseguirá gerenciar usuários, itens dos formulários e todos os itens da administração do sistema, competente ao seu orgão gestor.</p>
          </div>
        </div><!--/span-->
      </div><!--/row-->