
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <?if($this->institution == 1){?>
              <li class="nav-header">Usuários</li>
              <li><a href="/administration/user-new">Novo</a></li>
              <li><a href="/administration/user">Pesquisar</a></li>
              <li class="nav-header">Cadastros</li>
              <li><a href="/administration/city">Cidades</a></li>
              <li><a href="#">Autorização</a></li>
              <li><a href="#">Combustível</a></li>
              <li class="nav-header">Carros</li>
              <li><a href="#">Marcas de Carro</a></li>
              <li><a href="#">Modelos de Carro</a></li>
              <li class="nav-header">Taxímetros</li>
              <li><a href="#">Marcas de Táximetro</a></li>
              <li><a href="#">Modelos de Táximetro</a></li>
              <?}else if($this->institution == 2){?>
              <li class="nav-header">Fiscais</li>
              <li><a href="/administration/inspector-new">Cadastro</a></li>
              <li><a href="/administration/inspector">Pesquisa</a></li>
              <li class="nav-header">Fiscalização</li>
              <?}?>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1>Administração</h1>
            <p>Aqui você conseguirá gerenciar usuários, itens dos formulários e todos os itens da administração do sistema, competente ao seu orgão gestor.</p>
          </div>
        </div><!--/span-->
      </div><!--/row-->