<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
          <?if($this->institution == 1){?>
          <ul class="nav nav-list">
            <a href="/administration/user" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/city" class="list-group-item">
              <h4 class="list-group-item-heading">Cidades</h4>
            </a>
            <a href="/administration/city-new" class="list-group-item">Novo</a>
            <a href="/administration/city" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/model-vehicle" class="list-group-item">
              <h4 class="list-group-item-heading">Modelos de Carro</h4>
            </a>
            <a href="/administration/model-vehicle-new" class="list-group-item">Novo</a>
            <a href="/administration/model-vehicle" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/brand-vehicle" class="list-group-item">
              <h4 class="list-group-item-heading">Marcas de Carro</h4>
            </a>
            <a href="/administration/brand-vehicle-new" class="list-group-item">Novo</a>
            <a href="/administration/brand-vehicle" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/model-taximeter" class="list-group-item">
              <h4 class="list-group-item-heading">Modelos de Taxímetro</h4>
            </a>
            <a href="/administration/model-taximeter-new" class="list-group-item">Novo</a>
            <a href="/administration/model-taximeter" class="list-group-item">Pesquisar</a>
          </ul>
          <br>
          <ul class="nav nav-list">
            <a href="/administration/brand-taximeter" class="list-group-item">
              <h4 class="list-group-item-heading">Marcas de Táximetro</h4>
            </a>
            <a href="/administration/brand-taximeter-new" class="list-group-item">Novo</a>
            <a href="/administration/brand-taximeter" class="list-group-item">Pesquisar</a>
          </ul>
          <?}else if($this->institution == 2){?>
          <ul class="nav nav-list">
            <a href="/account" class="list-group-item">
              <h4 class="list-group-item-heading">Fiscais</h4>
            </a>
            <a href="/administration/brand-taximeter-new" class="list-group-item">Cadastro</a>
            <a href="/administration/brand-taximeter" class="list-group-item">Pesquisar</a>
          </ul>
          <?}?>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="col-md-9">
      <div class="jumbotron">
        <h1>Administração</h1>
        <p>Aqui você conseguirá gerenciar usuários, itens dos formulários e todos os itens da administração do sistema, competente ao seu orgão gestor.</p>
      </div>
    </div><!--/span-->
  </div><!--/row-->