<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">Fiscais</li>
          <li><a href="/administration/inspector-new">Cadastro</a></li>
          <li class="active"><a href="/administration/inspector">Pesquisa</a></li>
          <li class="nav-header">Fiscalização</li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Pesquisa <small>gerencie aqui os dados dos fiscais</small></h1>
      	<form class="form-search" action="/administration/inspector" method="get">
      		<input type="text" class="input-xlarge search-query" placeholder="pesquisa" name="field" value="<?=$this->field?>">
          <select name="optionSearch">
            <option value="0">Pesquisar por:</option>
            <option value="1" <?if($this->optionSearch == 1) echo "selected='selected'"; ?>>MASP</option>
            <option value="2" <?if($this->optionSearch == 2) echo "selected='selected'"; ?>>CPF</option>
            <option value="3" <?if($this->optionSearch == 3) echo "selected='selected'"; ?>>Nome</option>
          </select>
          <button type="submit" class="btn">Pesquisar</button>
      	</form>
      	<table class="table table-hover table-bordered">
      		<thead>
      			<th>Nome</th>
      			<th>MASP</th>
      			<th>CPF</th>
      		</thead>
      		<tbody>
      			<?if(is_object($this->list) && !isset($this->list->name)){
      				foreach($this->list as $inspector){?>
		      			<tr>
		      				<td><a href="/administration/inspector-edit/id/<?=$inspector->id?>"><?=$inspector->name?></a></td>
		      				<td><?=$inspector->masp?></td>
		      				<td><?=$inspector->cpf?></td>
		      			</tr>
      			<?} } else{?>
      				<tr>
      					<td colspan="7">Não encontrado nenhum fiscal na pesquisa.</td>
      				</tr>
      			<?}?>
      		</tbody>
      	</table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>