
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">Fiscais</li>
          <li class="active"><a href="/administration/inspector-new">Cadastro</a></li>
          <li><a href="/administration/inspector">Pesquisa</a></li>
          <li class="nav-header">Fiscalização</li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Novo Fiscal <small>defina aqui os dados do fiscal</small></h1>
        <hr>
        <?=$this->form?>
      </div>
    </div>
  </div><!--/span-->
</div><!--/row-->