
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">Usuários</li>
          <li class="active"><a href="/administration/user-new">Novo</a></li>
          <li><a href="/administration/user">Pesquisar</a></li>
          <li class="nav-header">Cidades</li>
          <li><a href="/administration/city-new">Novo</a></li>
          <li><a href="/administration/city">Pesquisa</a></li>
          <li class="nav-header">Combustível</li>
          <li><a href="#">Novo</a></li>
          <li><a href="#">Pesquisa</a></li>
          <li class="nav-header">Carros</li>
          <li><a href="#">Marcas de Carro</a></li>
          <li><a href="#">Modelos de Carro</a></li>
          <li class="nav-header">Taxímetros</li>
          <li><a href="#">Marcas de Táximetro</a></li>
          <li><a href="#">Modelos de Táximetro</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
        <h1>Novo Usuário <small>defina aqui os dados do usuário</small></h1>
        <hr>
        <?=$this->form?>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>