<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <title>SETOP | Táxi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/lib/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 80px;
      }

    </style>
    <link href="/css/lib/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/css/lib/font-awesome.min.css" rel="stylesheet">
    <link href="/css/lib/datepicker.css" rel="stylesheet">
    <link href="/css/lib/fullcalendar.css" rel="stylesheet">
    <link href="/css/lib/fullcalendar.print.css" rel="stylesheet">
    <script src="/js/lib/jquery-1.10.1.min.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/js/lib/html5shiv.js"></script>
      <script src="/js/lib/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <? 
      $authNamespace = new Zend_Session_Namespace('userInformation');
      $institution = $authNamespace->institution;
      $userId = $authNamespace->user_id; 
    ?>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/dashboard">SETOP | Táxi</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <?if($institution == 1){?>
              <li><a href="/grantee/view">Permissionários</a></li>
              <li><a href="/auxiliar/view">Auxiliares</a></li>
            <?}?>
            <?if($institution == 2){?>
              <li><a href="/inspection">Fiscalização</a></li>
              <li><a href="/survey">Vistoria</a></li>
            <?}?>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <?if($institution == 1){?>
            <li><a href="/scheduling">Agenda</a></li>
            <?}?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/account"><i class="icon-wrench"></i> Minha conta</a></li>
                <?if($userId == 1 || $userId == 5 || $userId == 9 || $userId == 6 || $userId == 11 || $userId == 12){?>
                <li> <a href="/administration"><i class="icon-eye-close"></i> Administração</a></li>
                <?}?>
                <li class="divider"></li>
                <li> <a href="/auth/logout"><i class="icon-signout"></i> Sair</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <?if($this->success){?>
      <div class="row">
        <div class="col-md-12 text-center alert alert-success fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ok!</strong> Dados atualizados com sucesso.
        </div>
      </div>
      <?}?>
      <?if($this->error){?>
      <div class="row">
        <div class="col-md-12 text-center alert alert-danger fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ops!</strong> Houve algum erro na inserção dos dados. Tente novamente preenchendo os dados corretamente.
        </div>
      </div>
      <?}?>
      <?if($this->password_error){?>
      <div class="row">
        <div class="col-md-12 text-center alert alert-danger fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ops!</strong> Senha antiga não confere ou senhas não conferem.
        </div>
      </div>
      <?}?>

      <?php echo $this->layout()->content; ?>

    </div>
    
    <script src="/js/lib/jquery-ui.custom.min.js"></script>
    <script src="/js/lib/jquery.maskedinput.min.js"></script>
    <script src="/js/lib/bootstrap.min.js"></script>
    <script src="/js/lib/bootstrap-datepicker.js"></script>
    <script src="/js/lib/underscore-min.js"></script>
    <script src="/js/language/pt-BR.js"></script>
    <script src="/js/lib/fullcalendar.js"></script>
    <script src="/js/lib/gcal.js"></script>
    <script src="/js/lib/jquery.livequery.js"></script>
    <script src="/js/lib/bootstrap3-typeahead.min.js"></script>
    <script src="/js/general.js"></script>
    <?if($institution == 1){?>
    <script src="/js/grantee_v2.js"></script>
    <script src="/js/auxiliar_v2.js"></script>
    <?}else{?>
    <script src="/js/assessment.js"></script>
    <?}?>
  </body>
</html>
