<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <title>SETOP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/datepicker.css" rel="stylesheet">

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="brand" href="/dashboard">Sistema de Controle de Táxi</a>
                <div class="btn-group pull-right">
                <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-user icon-white"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                <li>
                    <a href="/account">
                        <i class="icon-wrench"></i> Minha conta
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/auth/logout">
                        <i class="icon-signout"></i> Sair
                    </a>
                </li>
                </ul>
            </div>
            </div>
          </div>
        </div>


    <div class="container">

      <?if($this->success){?>
      <div class="row">
        <div class="span12 pagination-centered alert alert-success fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ok!</strong> Dados atualizados com sucesso.
        </div>
      </div>
      <?}?>
      <?if($this->error){?>
      <div class="row">
        <div class="span12 pagination-centered alert alert-error fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ops!</strong> Houve algum erro na inserção dos dados. Tente novamente preenchendo os dados corretamente.
        </div>
      </div>
      <?}?>
      <?if($this->password_error){?>
      <div class="row">
        <div class="span12 pagination-centered alert alert-error fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ops!</strong> Senha antiga não confere ou senhas não conferem.
        </div>
      </div>
      <?}?>

      <?php echo $this->layout()->content; ?>

    </div>
    
    <script src="/js/jquery-1.8.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-inputmask.min.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>
    <script src="/js/d3.v3.min.js"></script>
    <script src="/js/grantee.js"></script>
  </body>
</html>
