<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <title>SETOP | Táxi | Relatório</title>
    <!-- <link rel="stylesheet" type="text/css" href="css/general.css" media="screen"/> -->
    <style type="text/css" media="screen,print">
        table{ page-break-inside: avoid; position: relative;}
        @media print{
            table{page-break-inside: avoid; position: relative;}

        #navbar{
            width: 100%;
            height: 113px;
            padding: 0;
            display: inline;
        }
        }
    </style>
    
    <?php echo $this->layout()->content; ?>    
    <script src="/js/lib/jquery-ui.custom.min.js"></script>
    <script src="/js/lib/jquery.maskedinput.min.js"></script>
    <script src="/js/lib/bootstrap.min.js"></script>
    <script src="/js/lib/underscore-min.js"></script>
    <script src="/js/language/pt-BR.js"></script>
    <script src="/js/lib/fullcalendar.js"></script>
    <script src="/js/lib/gcal.js"></script>
    <script src="/js/lib/jquery.livequery.js"></script>
    <script src="/js/general.js"></script>
  </body>
</html>

