<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/grantee" class="list-group-item">
          <h4 class="list-group-item-heading">Permissionários</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos permissionários</p>
        </a>
        <a href="/grantee/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/grantee/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/grantee/report" class="list-group-item"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li class="active">Permissionário</li>
      </ol>  
      <div class="well">
        <img class="img-responsive img-thumbnail" src="/img/taxi_top.jpg"><br><br>
        <h1>Permissionário</h1>
        <p>O serviço público de transporte individual de passageiros por táxi especial metropolitano poderá ser prestado por terceiros mediante permissão, obtida por meio de licitação, respeitada a legislação vigente. </p>
      </div>
    </div>
  </div>
</div>