<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li> 
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="well">
        <img class="img-polaroid" src="/img/taxi_top.jpg"><br><br>
        <h1>Permissionário</h1>
        <p>O serviço público de transporte individual de passageiros por táxi especial metropolitano poderá ser prestado por terceiros mediante permissão, obtida por meio de licitação, respeitada a legislação vigente. </p>
      </div>
    </div>
  </div>
</div>