<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/grantee" class="list-group-item">
          <h4 class="list-group-item-heading">Permissionários</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos permissionários</p>
        </a>
        <a href="/grantee/new" class="list-group-item active"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/grantee/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/grantee/report" class="list-group-item"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/grantee">Permissionário</a></li>
        <li class="active">Novo</li>
      </ol>  
      <div class="page-header">
      	<h1>Novo Permissionário <small>defina aqui os dados do permissionário</small></h1>
        <hr>
        <form class="form-horizontal" action="/grantee/new" method="post">
        	<div>
	          <div class="panel-group" id="accordion1">
	          	<div class="panel panel-default">
	          		<div class="panel-heading">
	          			<h4 class="panel-title">
	          				<a class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapseMain">Dados Principais</a>
          				</h4>
	          		</div>
	          		<div id="collapseMain" class="panel-collapse collapse in">
	          			<div class="panel-body">
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="name">Nome</label>
					              <div class="col-lg-5">
					                  <input type="text" name="name" value="" class="form-control" id="name" placeholder="nome completo">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="permission">Permissão</label>
					              <div class="col-lg-5">
					                  <input type="text" name="permission" value="" class="form-control permission" id="permission" placeholder="número da permissão">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="authorization">Autorização</label>
					              <div class="col-lg-5">
					                  <select name="authorization" id="authorization" class="form-control">
					                  	<option value="0">-- Escolha o tipo de autorização --</option>
					                  	<option value="1">Táxi Especial</option>
					                  </select>
					              </div><!--/.controls -->
					            </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="city">Cidade</label>
					              <div class="col-lg-5">
				                  <select name="city" id="city" class="form-control">
				                  	<option value="0">-- Escolha o município --</option>
				                  	<?foreach ($this->cities as $city){ ?>
				                  	<option value="<?=$city->id?>"><?=$city->name?></option>
				                  	<?}?>
				                  </select>
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="start_permission">Início da permissão</label>
					              <div class="col-lg-5">
					                  <input type="text" name="start_permission" value="" class="form-control dateMask" id="start_permission" placeholder="data de início da permissão">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="end_permission">Término da permissão</label>
					              <div class="col-lg-5">
					                  <input type="text" name="end_permission" value="" class="form-control dateMask" id="end_permission" placeholder="data de término da permissão">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="info">Observações</label>
					              <div class="col-lg-5">
					                  <textarea type="text" name="info" rows="5" class="form-control" id="info" placeholder="observações"></textarea>
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="pendencies">Pendências</label>
					              <div class="col-lg-5">
					                  <textarea type="text" name="pendencies" rows="5" class="form-control" id="pendencies" placeholder="pendências"></textarea>
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					        </div>
					      </div>
					    </div>
	          	<div class="panel panel-default">
	          		<div class="panel-heading">
	          			<h4 class="panel-title">
	          				<a class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapseAddress">Endereço</a>
	          			</h4>
	          		</div>
	          		<div id="collapseAddress" class="panel-collapse collapse">
	          			<div class="panel-collapse">
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="address">Endereço</label>
					              <div class="col-lg-5">
					                  <input type="text" name="address" value="" class="form-control" id="address" placeholder="logradouro">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="number">Número</label>
					              <div class="col-lg-5">
					                  <input type="text" name="number" value="" class="form-control" id="number" placeholder="número">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="apartament">Complemento</label>
					              <div class="col-lg-5">
					                  <input type="text" name="apartament" value="" class="form-control" id="apartament" placeholder="complemento">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="neighborhood">Bairro</label>
					              <div class="col-lg-5">
					                  <input type="text" name="neighborhood" value="" class="form-control" id="neighborhood" placeholder="bairro">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="address_city">Cidade</label>
					              <div class="col-lg-5">
					                  <select name="address_city" id="address_city" class="form-control">
					                  	<option value="0">-- Escolha o município --</option>
					                  	<?foreach ($this->cities as $city){ ?>
					                  	<option value="<?=$city->id?>"><?=$city->name?></option>
					                  	<?}?>
					                  </select>
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="zipcode">CEP</label>
					              <div class="col-lg-5">
					                  <input type="text" name="zipcode" value="" class="form-control zipcode" id="zipcode" placeholder="cep">
					              </div><!--/.controls -->
					          </div><!--/.form-group -->
	          			</div>
	          		</div>
	          	</div>
	          	<div class="panel panel-default">
	          		<div class="panel-heading">
	          			<h4 class="panel-title">
	          				<a class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapseContact">Contato</a>
          				</h4>
	          		</div>
	          		<div id="collapseContact" class="panel-collapse collapse">
	          			<div class="panel-body">
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="phone">Telefone fixo</label>
					              <div class="col-lg-5">
					                  <input type="text" name="phone" value="" class="form-control phone" id="phone" placeholder="telefone fixo">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="mobile">Celular</label>
					              <div class="col-lg-5">
					                  <input type="text" name="mobile" value="" class="form-control phone" id="mobile" placeholder="celular">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="email">Email</label>
					              <div class="col-lg-5">
					                  <input type="text" name="email" value="" class="form-control" id="email" placeholder="email">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          			</div>
	          		</div>
	          	</div>
		          <div class="panel panel-default">
		        		<div class="panel-heading">
		        			<h4 class="panel-title">
		        				<a class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapseDocument">Documentos</a>
	        				</h4>
		        		</div>
		        		<div id="collapseDocument" class="panel-collapse collapse">
		        			<div class="panel-body">
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="rg">Identidade</label>
					              <div class="col-lg-5">
					                  <input type="text" name="rg" value="" class="form-control" id="rg" placeholder="identidade">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="rg_issuer">Orgão Emissor da Identidade</label>
					              <div class="col-lg-5">
					                  <input type="text" name="rg_issuer" value="" class="form-control" id="rg_issuer" placeholder="orgão emissor da identidade">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="cpf">CPF</label>
					              <div class="col-lg-5">
					                  <input type="text" name="cpf" value="" class="form-control cpf" id="cpf" placeholder="cpf">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="cnh">Habilitação</label>
					              <div class="col-lg-5">
					                  <input type="text" name="cnh" value="" class="form-control" id="cnh" placeholder="habilitação">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="cnh_issuer">Orgão Emissor da Habilitação</label>
					              <div class="col-lg-5">
					                  <input type="text" name="cnh_issuer" value="" class="form-control" id="cnh_issuer" placeholder="orgão emissor da habilitação">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="iapas">IAPAS</label>
					              <div class="col-lg-5">
					                  <input type="text" name="iapas" value="" class="form-control" id="iapas" placeholder="iapas">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="voter">Título de Eleitor</label>
					              <div class="col-lg-5">
					                  <input type="text" name="voter" value="" class="form-control" id="voter" placeholder="título de eleitor">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="voter_zone">Zona Eleitoral</label>
					              <div class="col-lg-5">
					                  <input type="text" name="voter_zone" value="" class="form-control" id="voter_zone" placeholder="zona eleitoral">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="army">Militar</label>
					              <div class="col-lg-5">
					                  <input type="text" name="army" value="" class="form-control" id="army" placeholder="documento militar">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
					          <div class="form-group">
					              <label class="col-lg-2 control-label" for="army_issuer">Orgão Emissor Militar</label>
					              <div class="col-lg-5">
					                  <input type="text" name="army_issuer" value="" class="form-control" id="army_issuer" placeholder="orgão emissor do documento militar">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
		        			</div>
		        		</div>
		        	</div>
		        	<div class="panel panel-default">
	          		<div class="panel-heading">
	          			<h4 class="panel-title">
	          				<a class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapseVehicle">Veículo</a>
          				</h4>
	          		</div>
	          		<div id="collapseVehicle" class="panel-collapse collapse">
	          			<div class="panel-body">
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="plate">Placa</label>
					              <div class="col-lg-5">
					                  <input type="text" name="plate" value="" class="form-control plate" id="plate" placeholder="placa">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="brand">Marca</label>
					              <div class="col-lg-5">
				                   <select  class="form-control" name="brand">
					                 	<option value="0">-- Selecione uma marca --</option>
					                 	 <?foreach($this->vehicleBrand as $vehicleBrand){?>
					                 		<option value="<?=$vehicleBrand->id?>"><?=$vehicleBrand->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="model">Modelo</label>
					              <div class="col-lg-5">
					                 <select  class="form-control" name="model">
					                 		<option value="0">-- Selecione um modelo --</option>
					                 	<?foreach($this->vehicleModel as $vehicleModel){?>
					                 		<option value="<?=$vehicleModel->id?>"><?=$vehicleModel->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="year_fabrication">Ano Fabricação</label>
					              <div class="col-lg-5">
					                  <input type="text" name="year_fabrication" value="" class="form-control" id="year_fabrication" placeholder="ano de fabricação" data-mask="9999">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="year_model">Ano Modelo</label>
					              <div class="col-lg-5">
					                  <input type="text" name="year_model" value="" class="form-control" id="year_model" placeholder="ano do modelo" data-mask="9999">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="color">Cor</label>
					              <div class="col-lg-5">
					                  <input type="text" name="color" value="" class="form-control" id="color" placeholder="cor">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="chassi">Chassi</label>
					              <div class="col-lg-5">
					                  <input type="text" name="chassi" value="" class="form-control" id="chassi" placeholder="chassi">
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="fuel">Tipo de Combustivel</label>
					              <div class="col-lg-5">
				                   <select  class="form-control" name="fuel">
					                 	<option value="0">-- Selecione um combustivel --</option>
					                 	<option value="1">Alcool/Gnv</option>
					                 	<option value="2">Gasolina/Alcool</option>
					                 	<option value="3">Gasolina/Gnv</option>
					                 	<option value="4">Alcool</option>
					                 	<option value="5">Gasolina/Alcool/Gnv</option>
					                 	<option value="6">Gasolina</option>
					                 </select>
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="taximeter_brand">Taxímetro Marca</label>
					              <div class="col-lg-5">
				                   <select  class="form-control" name="taximeter_brand">
					                 	<option value="0">-- Selecione uma marca --</option>
					                 	<?foreach($this->brandTaximeter as $brandTaximeter){?>
					                 		<option value="<?=$brandTaximeter->id?>"><?=$brandTaximeter->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          				<div class="form-group">
					              <label class="col-lg-2 control-label" for="taximeter_model">Taxímetro Modelo</label>
					              <div class="col-lg-5">
				                   <select  class="form-control" name="taximeter_model">
					                 	<option value="0">-- Selecione um modelo --</option>
					                 	<?foreach($this->modelTaximeter as $modelTaximeter){?>
					                 		<option value="<?=$modelTaximeter->id?>"><?=$modelTaximeter->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.col-lg-5 -->
					          </div><!--/.form-group -->
	          			</div>
	          		</div>
	          	</div>
		        </div>
		      </div><br>
          <div class="form-group">
          	<div class="col-lg-5">
              <button type="submit" class="col-lg-offset-2 btn btn-primary">Salvar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>