<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li class="active"><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li>
        <li><a href="/grantee/vis"><i class="icon-picture"></i> Visualização </a></li><!-- 
        <li><a href="#"><i class="icon-picture"></i> Emissão de Carteiras </a></li>
        <li><a href="#"><i class="icon-wrench"></i> Guias de Recolhimento </a></li> -->
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Novo Permissionário <small>defina aqui os dados do permissionário</small></h1>
        <hr>
        <form class="form-horizontal" action="/grantee/new" method="post">
        	<div class="control-group">
	          <div class="accordion" id="acoordion1">
	          	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseMain">Dados Principais</a>
	          		</div>
	          		<div id="collapseMain" class="accordion-body collapse in">
	          			<div class="accordion-inner">
					          <div class="control-group">
					              <label class="control-label" for="name">Nome</label>
					              <div class="controls">
					                  <input type="text" name="name" value="" class="input-xlarge" id="name" placeholder="nome completo">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="permission">Permissão</label>
					              <div class="controls">
					                  <input type="text" name="permission" value="" class="input-xlarge" id="permission" placeholder="número da permissão">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="authorization">Autorização</label>
					              <div class="controls">
					                  <select name="authorization" id="authorization" class="input-xlarge">
					                  	<option value="0">-- Escolha o tipo de autorização --</option>
					                  	<option value="1">Táxi Especial</option>
					                  </select>
					              </div><!--/.controls -->
					            </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="city">Cidade</label>
					              <div class="controls">
				                  <select name="city" id="city" class="input-xlarge">
				                  	<option value="0">-- Escolha o município --</option>
				                  	<option value="1">Belo Horizonte</option>
				                  	<option value="2">Sete Lagoas</option>
				                  	<option value="3">Contagem</option>
				                  	<option value="4">Betim</option>
				                  	<option value="5">Santa Luzia</option>
				                  	<option value="6">Sabará</option>
				                  	<option value="7">Caeté</option>
				                  	<option value="8">Confins</option>
				                  	<option value="9">Ibirité</option>
				                  	<option value="10">Nova Lima</option>
				                  	<option value="11">Rio Acima</option>
				                  	<option value="12">Ribeirão das Neves</option>
				                  	<option value="13">Raposos</option>
				                  	<option value="14">Vespasiano</option>
				                  	<option value="15">Pedro Leopoldo</option>
				                  </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="start_permission">Início da permissão</label>
					              <div class="controls">
					                  <input type="text" name="start_permission" value="" class="input-xlarge" id="start_permission" placeholder="data de início da permissão">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					        </div>
					      </div>
					    </div>
	          	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseAddress">Endereço</a>
	          		</div>
	          		<div id="collapseAddress" class="accordion-body collapse">
	          			<div class="accordion-inner">
	          				<div class="control-group">
					              <label class="control-label" for="address">Endereço</label>
					              <div class="controls">
					                  <input type="text" name="address" value="" class="input-xlarge" id="address" placeholder="logradouro">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="number">Número</label>
					              <div class="controls">
					                  <input type="text" name="number" value="" class="input-xlarge" id="number" placeholder="número">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="apartament">Complemento</label>
					              <div class="controls">
					                  <input type="text" name="apartament" value="" class="input-xlarge" id="apartament" placeholder="complemento">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="neighborhood">Bairro</label>
					              <div class="controls">
					                  <input type="text" name="neighborhood" value="" class="input-xlarge" id="neighborhood" placeholder="bairro">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="address_city">Cidade</label>
					              <div class="controls">
					                  <select name="address_city" id="address_city" class="input-xlarge">
					                  	<option value="0">-- Escolha o município --</option>
					                  	<option value="1">Belo Horizonte</option>
					                  	<option value="2">Sete Lagoas</option>
					                  	<option value="3">Contagem</option>
					                  	<option value="4">Betim</option>
					                  	<option value="5">Santa Luzia</option>
					                  	<option value="6">Sabará</option>
					                  	<option value="7">Caeté</option>
					                  	<option value="8">Confins</option>
					                  	<option value="9">Ibirité</option>
					                  	<option value="10">Nova Lima</option>
					                  	<option value="11">Rio Acima</option>
					                  	<option value="12">Ribeirão das Neves</option>
					                  	<option value="13">Raposos</option>
					                  	<option value="14">Vespasiano</option>
					                  	<option value="15">Pedro Leopoldo</option>
					                  </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="zipcode">CEP</label>
					              <div class="controls">
					                  <input type="text" name="zipcode" value="" class="input-xlarge" id="zipcode" placeholder="cep">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          			</div>
	          		</div>
	          	</div>
	          	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseContact">Contato</a>
	          		</div>
	          		<div id="collapseContact" class="accordion-body collapse">
	          			<div class="accordion-inner">
	          				<div class="control-group">
					              <label class="control-label" for="phone">Telefone fixo</label>
					              <div class="controls">
					                  <input type="text" name="phone" value="" class="input-xlarge" id="phone" placeholder="telefone fixo">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="mobile">Celular</label>
					              <div class="controls">
					                  <input type="text" name="mobile" value="" class="input-xlarge" id="mobile" placeholder="celular">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="email">Email</label>
					              <div class="controls">
					                  <input type="text" name="email" value="" class="input-xlarge" id="email" placeholder="email">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          			</div>
	          		</div>
	          	</div>
		          <div class="accordion-group">
		        		<div class="accordion-heading">
		        			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseDocument">Documentos</a>
		        		</div>
		        		<div id="collapseDocument" class="accordion-body collapse">
		        			<div class="accordion-inner">
					          <div class="control-group">
					              <label class="control-label" for="rg">Identidade</label>
					              <div class="controls">
					                  <input type="text" name="rg" value="" class="input-xlarge" id="rg" placeholder="identidade">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="rg_issuer">Orgão Emissor da Identidade</label>
					              <div class="controls">
					                  <input type="text" name="rg_issuer" value="" class="input-xlarge" id="rg_issuer" placeholder="orgão emissor da identidade">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="cpf">CPF</label>
					              <div class="controls">
					                  <input type="text" name="cpf" value="" class="input-xlarge" id="cpf" placeholder="cpf">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="cnh">Habilitação</label>
					              <div class="controls">
					                  <input type="text" name="cnh" value="" class="input-xlarge" id="cnh" placeholder="habilitação">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="cnh_issuer">Orgão Emissor da Habilitação</label>
					              <div class="controls">
					                  <input type="text" name="cnh_issuer" value="" class="input-xlarge" id="cnh_issuer" placeholder="orgão emissor da habilitação">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="iapas">IAPAS</label>
					              <div class="controls">
					                  <input type="text" name="iapas" value="" class="input-xlarge" id="iapas" placeholder="iapas">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="voter">Título de Eleitor</label>
					              <div class="controls">
					                  <input type="text" name="voter" value="" class="input-xlarge" id="voter" placeholder="título de eleitor">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="voter_zone">Zona Eleitoral</label>
					              <div class="controls">
					                  <input type="text" name="voter_zone" value="" class="input-xlarge" id="voter_zone" placeholder="zona eleitoral">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="army">Militar</label>
					              <div class="controls">
					                  <input type="text" name="army" value="" class="input-xlarge" id="army" placeholder="documento militar">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="army_issuer">Orgão Emissor Militar</label>
					              <div class="controls">
					                  <input type="text" name="army_issuer" value="" class="input-xlarge" id="army_issuer" placeholder="orgão emissor do documento militar">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
		        			</div>
		        		</div>
		        	</div>
		        	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseVehicle">Veículo</a>
	          		</div>
	          		<div id="collapseVehicle" class="accordion-body collapse">
	          			<div class="accordion-inner">
	          				<div class="control-group">
					              <label class="control-label" for="plate">Placa</label>
					              <div class="controls">
					                  <input type="text" name="plate" value="" class="input-xlarge" id="plate" placeholder="placa">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="brand">Marca</label>
					              <div class="controls">
				                   <select name="brand">
					                 	<option value="0">-- Selecione uma marca --</option>
					                 	 <option value="1">Citroën</option>
														 <option value="2">GM</option>
														 <option value="3">Fiat</option>
														 <option value="4">Ford</option>
														 <option value="5">Honda</option>
														 <option value="6">Peugeot</option>
														 <option value="7">Renault</option>
														 <option value="8">Toyota</option>
														 <option value="9">Volkswagen</option>
														 <option value="10">Citroën</option>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="model">Modelo</label>
					              <div class="controls">
					                 <select name="model">
					                 	<option value="0">-- Selecione um modelo --</option>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="year_fabrication">Ano Fabricação</label>
					              <div class="controls">
					                  <input type="text" name="year_fabrication" value="" class="input-xlarge" id="year_fabrication" placeholder="ano de fabricação">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="year_model">Ano Modelo</label>
					              <div class="controls">
					                  <input type="text" name="year_model" value="" class="input-xlarge" id="year_model" placeholder="ano do modelo">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="color">Cor</label>
					              <div class="controls">
					                  <input type="text" name="color" value="" class="input-xlarge" id="color" placeholder="cor">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="chassi">Chassi</label>
					              <div class="controls">
					                  <input type="text" name="chassi" value="" class="input-xlarge" id="chassi" placeholder="chassi">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="fuel">Tipo de Combustivel</label>
					              <div class="controls">
				                   <select name="fuel">
					                 	<option value="0">-- Selecione um combustivel --</option>
					                 	<option value="1">Gasolina</option>
					                 	<option value="2">Alcool</option>
					                 	<option value="3">Gás</option>
					                 	<option value="4">Flex</option>
					                 	<option value="5">Diesel</option>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="taximeter_model">Taxímetro Modelo</label>
					              <div class="controls">
				                   <select name="taximeter_model">
					                 	<option value="0">-- Selecione um modelo --</option>
					                 	<option value="1">B-3</option>
					                 	<option value="2">Cap-z</option>
					                 	<option value="3">Dijotax</option>
					                 	<option value="4">Dijotax 31</option>
					                 	<option value="5">Fib/97</option>
					                 	<option value="6">Fip</option>
					                 	<option value="7">Fip LL</option>
					                 	<option value="8">Micro XT</option>
					                 	<option value="9">Mig LLL</option>
					                 	<option value="10">Mini Mig</option>
					                 	<option value="11">Sm 2000</option>
					                 	<option value="12">XI-5</option>
					                 	<option value="13">XT-5</option>
					                 	<option value="14">XT-5 Mini</option>
					                 	<option value="16">6 AT</option>
					                 	<option value="17">CAP 2</option>
					                 	<option value="18">15 Mini</option>
					                 	<option value="19">6 II</option>
					                 	<option value="20">Fib At</option>
					                 	<option value="21">1 Milenium</option>
					                 	<option value="22">Uel/ Vr 11</option>
					                 	<option value="23">1 Printer</option>
					                 	<option value="24">Slim</option>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="taximeter_brand">Taxímetro Marca</label>
					              <div class="controls">
				                   <select name="taximeter_brand">
					                 	<option value="0">-- Selecione uma marca --</option>
					                 	<option value="1">Arco</option>
					                 	<option value="2">Bossa</option>
					                 	<option value="3">Brasilcotax</option>
					                 	<option value="4">Capelinha</option>
					                 	<option value="5">D. Bell</option>
					                 	<option value="6">Digitax</option>
					                 	<option value="7">Fumaça</option>
					                 	<option value="8">Metron</option>
					                 	<option value="9">Micromac</option>
					                 	<option value="10">Mig</option>
					                 	<option value="11">Silmar</option>
					                 	<option value="12">União</option>
					                 	<option value="13">Univertax</option>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          			</div>
	          		</div>
	          	</div>
		        </div>
		      </div>
          <div class="form-actions">
              <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>