<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li class="active"><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li>
        <li><a href="/grantee/vis"><i class="icon-bar-chart"></i> Visualização </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Novo Permissionário <small>defina aqui os dados do permissionário</small></h1>
        <hr>
        <form class="form-horizontal" action="/grantee/new" method="post">
        	<div class="control-group">
	          <div class="accordion" id="acoordion1">
	          	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseMain">Dados Principais</a>
	          		</div>
	          		<div id="collapseMain" class="accordion-body collapse in">
	          			<div class="accordion-inner">
					          <div class="control-group">
					              <label class="control-label" for="name">Nome</label>
					              <div class="controls">
					                  <input type="text" name="name" value="" class="input-xlarge" id="name" placeholder="nome completo">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="permission">Permissão</label>
					              <div class="controls">
					                  <input type="text" name="permission" value="" class="input-xlarge permission" id="permission" placeholder="número da permissão">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="authorization">Autorização</label>
					              <div class="controls">
					                  <select name="authorization" id="authorization" class="input-xlarge">
					                  	<option value="0">-- Escolha o tipo de autorização --</option>
					                  	<option value="1">Táxi Especial</option>
					                  </select>
					              </div><!--/.controls -->
					            </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="city">Cidade</label>
					              <div class="controls">
				                  <select name="city" id="city" class="input-xlarge">
				                  	<option value="0">-- Escolha o município --</option>
				                  	<?foreach ($this->cities as $city){ ?>
				                  	<option value="<?=$city->id?>"><?=$city->name?></option>
				                  	<?}?>
				                  </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="start_permission">Início da permissão</label>
					              <div class="controls">
					                  <input type="text" name="start_permission" value="" class="input-xlarge dateMask" id="start_permission" placeholder="data de início da permissão">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="end_permission">Término da permissão</label>
					              <div class="controls">
					                  <input type="text" name="end_permission" value="" class="input-xlarge dateMask" id="end_permission" placeholder="data de término da permissão">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="info">Observações</label>
					              <div class="controls">
					                  <textarea type="text" name="info" rows="5" class="input-xlarge" id="info" placeholder="observações"></textarea>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="pendencies">Pendências</label>
					              <div class="controls">
					                  <textarea type="text" name="pendencies" rows="5" class="input-xlarge" id="pendencies" placeholder="pendências"></textarea>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					        </div>
					      </div>
					    </div>
	          	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseAddress">Endereço</a>
	          		</div>
	          		<div id="collapseAddress" class="accordion-body collapse">
	          			<div class="accordion-inner">
	          				<div class="control-group">
					              <label class="control-label" for="address">Endereço</label>
					              <div class="controls">
					                  <input type="text" name="address" value="" class="input-xlarge" id="address" placeholder="logradouro">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="number">Número</label>
					              <div class="controls">
					                  <input type="text" name="number" value="" class="input-xlarge" id="number" placeholder="número">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="apartament">Complemento</label>
					              <div class="controls">
					                  <input type="text" name="apartament" value="" class="input-xlarge" id="apartament" placeholder="complemento">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="neighborhood">Bairro</label>
					              <div class="controls">
					                  <input type="text" name="neighborhood" value="" class="input-xlarge" id="neighborhood" placeholder="bairro">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="address_city">Cidade</label>
					              <div class="controls">
					                  <select name="address_city" id="address_city" class="input-xlarge">
					                  	<option value="0">-- Escolha o município --</option>
					                  	<?foreach ($this->cities as $city){ ?>
					                  	<option value="<?=$city->id?>"><?=$city->name?></option>
					                  	<?}?>
					                  </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="zipcode">CEP</label>
					              <div class="controls">
					                  <input type="text" name="zipcode" value="" class="input-xlarge zipcode" id="zipcode" placeholder="cep">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          			</div>
	          		</div>
	          	</div>
	          	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseContact">Contato</a>
	          		</div>
	          		<div id="collapseContact" class="accordion-body collapse">
	          			<div class="accordion-inner">
	          				<div class="control-group">
					              <label class="control-label" for="phone">Telefone fixo</label>
					              <div class="controls">
					                  <input type="text" name="phone" value="" class="input-xlarge phone" id="phone" placeholder="telefone fixo">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="mobile">Celular</label>
					              <div class="controls">
					                  <input type="text" name="mobile" value="" class="input-xlarge phone" id="mobile" placeholder="celular">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="email">Email</label>
					              <div class="controls">
					                  <input type="text" name="email" value="" class="input-xlarge" id="email" placeholder="email">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          			</div>
	          		</div>
	          	</div>
		          <div class="accordion-group">
		        		<div class="accordion-heading">
		        			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseDocument">Documentos</a>
		        		</div>
		        		<div id="collapseDocument" class="accordion-body collapse">
		        			<div class="accordion-inner">
					          <div class="control-group">
					              <label class="control-label" for="rg">Identidade</label>
					              <div class="controls">
					                  <input type="text" name="rg" value="" class="input-xlarge" id="rg" placeholder="identidade">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="rg_issuer">Orgão Emissor da Identidade</label>
					              <div class="controls">
					                  <input type="text" name="rg_issuer" value="" class="input-xlarge" id="rg_issuer" placeholder="orgão emissor da identidade">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="cpf">CPF</label>
					              <div class="controls">
					                  <input type="text" name="cpf" value="" class="input-xlarge cpf" id="cpf" placeholder="cpf">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="cnh">Habilitação</label>
					              <div class="controls">
					                  <input type="text" name="cnh" value="" class="input-xlarge" id="cnh" placeholder="habilitação">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="cnh_issuer">Orgão Emissor da Habilitação</label>
					              <div class="controls">
					                  <input type="text" name="cnh_issuer" value="" class="input-xlarge" id="cnh_issuer" placeholder="orgão emissor da habilitação">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="iapas">IAPAS</label>
					              <div class="controls">
					                  <input type="text" name="iapas" value="" class="input-xlarge" id="iapas" placeholder="iapas">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="voter">Título de Eleitor</label>
					              <div class="controls">
					                  <input type="text" name="voter" value="" class="input-xlarge" id="voter" placeholder="título de eleitor">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="voter_zone">Zona Eleitoral</label>
					              <div class="controls">
					                  <input type="text" name="voter_zone" value="" class="input-xlarge" id="voter_zone" placeholder="zona eleitoral">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="army">Militar</label>
					              <div class="controls">
					                  <input type="text" name="army" value="" class="input-xlarge" id="army" placeholder="documento militar">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
					          <div class="control-group">
					              <label class="control-label" for="army_issuer">Orgão Emissor Militar</label>
					              <div class="controls">
					                  <input type="text" name="army_issuer" value="" class="input-xlarge" id="army_issuer" placeholder="orgão emissor do documento militar">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
		        			</div>
		        		</div>
		        	</div>
		        	<div class="accordion-group">
	          		<div class="accordion-heading">
	          			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseVehicle">Veículo</a>
	          		</div>
	          		<div id="collapseVehicle" class="accordion-body collapse">
	          			<div class="accordion-inner">
	          				<div class="control-group">
					              <label class="control-label" for="plate">Placa</label>
					              <div class="controls">
					                  <input type="text" name="plate" value="" class="input-xlarge plate" id="plate" placeholder="placa">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="brand">Marca</label>
					              <div class="controls">
				                   <select name="brand">
					                 	<option value="0">-- Selecione uma marca --</option>
					                 	 <?foreach($this->vehicleBrand as $vehicleBrand){?>
					                 		<option value="<?=$vehicleBrand->id?>"><?=$vehicleBrand->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="model">Modelo</label>
					              <div class="controls">
					                 <select name="model">
					                 		<option value="0">-- Selecione um modelo --</option>
					                 	<?foreach($this->vehicleModel as $vehicleModel){?>
					                 		<option value="<?=$vehicleModel->id?>"><?=$vehicleModel->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="year_fabrication">Ano Fabricação</label>
					              <div class="controls">
					                  <input type="text" name="year_fabrication" value="" class="input-xlarge" id="year_fabrication" placeholder="ano de fabricação" data-mask="9999">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="year_model">Ano Modelo</label>
					              <div class="controls">
					                  <input type="text" name="year_model" value="" class="input-xlarge" id="year_model" placeholder="ano do modelo" data-mask="9999">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="color">Cor</label>
					              <div class="controls">
					                  <input type="text" name="color" value="" class="input-xlarge" id="color" placeholder="cor">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="chassi">Chassi</label>
					              <div class="controls">
					                  <input type="text" name="chassi" value="" class="input-xlarge" id="chassi" placeholder="chassi">
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="fuel">Tipo de Combustivel</label>
					              <div class="controls">
				                   <select name="fuel">
					                 	<option value="0">-- Selecione um combustivel --</option>
					                 	<option value="1">Alcool/Gnv</option>
					                 	<option value="2">Gasolina/Alcool</option>
					                 	<option value="3">Gasolina/Gnv</option>
					                 	<option value="4">Alcool</option>
					                 	<option value="5">Gasolina/Alcool/Gnv</option>
					                 	<option value="6">Gasolina</option>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="taximeter_brand">Taxímetro Marca</label>
					              <div class="controls">
				                   <select name="taximeter_brand">
					                 	<option value="0">-- Selecione uma marca --</option>
					                 	<?foreach($this->brandTaximeter as $brandTaximeter){?>
					                 		<option value="<?=$brandTaximeter->id?>"><?=$brandTaximeter->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          				<div class="control-group">
					              <label class="control-label" for="taximeter_model">Taxímetro Modelo</label>
					              <div class="controls">
				                   <select name="taximeter_model">
					                 	<option value="0">-- Selecione um modelo --</option>
					                 	<?foreach($this->modelTaximeter as $modelTaximeter){?>
					                 		<option value="<?=$modelTaximeter->id?>"><?=$modelTaximeter->name?></option>
					                 	<?}?>
					                 </select>
					              </div><!--/.controls -->
					          </div><!--/.control-group -->
	          			</div>
	          		</div>
	          	</div>
		        </div>
		      </div>
          <div class="form-actions">
              <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>