<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li class="active"><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li> 
        <li><a href="/grantee/vis"><i class="icon-bar-chart"></i> Visualização </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Lista Completa</h2>
          <p>Lista completa dos permissionários com seus principais dados.</p>
          <p><a href="/grantee/report-grantee-all" class="btn">emitir relatório</a></p>
        </div>
        <div class="span6 well">
          <h2>Lista Ativos</h2>
          <p>Lista completa de todos os permissionários ativos no sistema.</p>
          <p><a href="/grantee/report-grantee-actives" class="btn">emitir relatório</a></p>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Veículos</h2>
          <p>Lista de todos veículos vinculados aos permissionários. </p>
          <p><a href="/grantee/report-vehicle" class="btn">emitir relatório</a></p>
        </div>
        <div class="span6 well">
          <h2>Pendências</h2>
          <p>Lista das pendências dos permissionários.</p>
          <p><a href="#" class="btn">emitir relatório</a></p>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Pontuação</h2>
          <p>Lista da pontuação dos permissionários.</p>
          <p><a href="#" class="btn">emitir relatório</a></p>
        </div>
      </div>
    </div>
  </div>
</div>