<div class="container">
  <div id="navbar"><img src="/img/superintendencia.jpg">
    <div class="row">
      <table class="table table-bordered table-hover" border='1'>
        <thead>
          <tr> 
            <th> Permissão</th>
            <th> Marca</th>
            <th> Modelo </th>
            <th> Fabricação do Veículo</th>
            <th> Ano do Modelo do Veículo</th>
            <th> Combustivel</th>
            <th> Vida Útil</th>
          </tr>
        </thead>
        <tbody>
            <?if(count($this->list))
            {?>
              <?foreach($this->list as $vehicle)
                {?>
                    <tr>
                      <td><?=$vehicle->permission?></td>
                      <td><?=$vehicle->vehicle_brand?></td>
                      <td><?=$vehicle->vehicle_model?></td>
                      <td><?=$vehicle->year_fabrication?></td>
                      <td><?=$vehicle->year_model?></td>
                      <td><?=$vehicle->vehicle_fuel?></td>
                      <td><?=$vehicle->life_cycle?></td>
                    </tr> 
                    <?}
            }?>
        </tbody>
      </table>
    </div>  
  </div>  
</div>