<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/grantee" class="list-group-item">
          <h4 class="list-group-item-heading">Permissionários</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos permissionários</p>
        </a>
        <a href="/grantee/new" class="list-group-item"><span class="glyphicon glyphicon-user"></span> Novo</a>
        <a href="/grantee/view" class="list-group-item"><span class="glyphicon glyphicon-bullhorn"></span> Pesquisa</a>
        <a href="/grantee/report" class="list-group-item active"><span class="glyphicon glyphicon-map-marker"></span> Relatórios</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/grantee">Permissionário</a></li>
        <li class="active">Relatórios</li>
      </ol>  
      <div class="row">
        <div class="span4 well">
          <h2>Lista Completa</h2>
          <p>Lista completa dos permissionários com seus principais dados.</p>
          <p><a href="/grantee/report-grantee-all" class="btn btn-default">emitir relatório</a></p>
        </div>
        <div class="span4 well">
          <h2>Lista Ativos</h2>
          <p>Lista completa de todos os permissionários ativos no sistema.</p>
          <p><a href="/grantee/report-grantee-actives" class="btn btn-default">emitir relatório</a></p>
        </div>
      </div>
      <div class="row">
        <div class="span4 well">
          <h2>Veículos</h2>
          <p>Lista de todos veículos vinculados aos permissionários. </p>
          <p><a href="/grantee/report-vehicle" class="btn btn-default">emitir relatório</a></p>
        </div>
        <div class="span4 well">
          <h2>Pendências</h2>
          <p>Lista das pendências dos permissionários.</p>
          <p><a href="#" class="btn btn-default">emitir relatório</a></p>
        </div>
      </div>
      <div class="row">
        <div class="span4 well">
          <h2>Pontuação</h2>
          <p>Lista da pontuação dos permissionários.</p>
          <p><a href="#" class="btn btn-default">emitir relatório</a></p>
        </div>
      </div>
    </div>
  </div>
</div>