<div class="container">
  <div id="navbar"><img src="/img/superintendencia.jpg">
    <div class="row">
      <div class="col-xs-8">
        <table class="table table-bordered table-hover" border='1'>
          <thead>
            <tr> 
              <th> Modelo</th>
              <th> Nº de veiculos</th>
              <th> Vida útil média</th>
              <th> Marca</th>
              </tr>
          </thead>
          <tbody>
              <?if(count($this->list2))
              {?>
                <?foreach($this->list2 as $vehicle)
                  {?>
                      <tr>
                        <td><?=$vehicle->vehicle_model?></td>
                        <td><?=$vehicle->vehicle_model_num?></td>
                        <td><?=$vehicle->life_cycle?></td>
                        <td><?=$vehicle->vehicle_brand?></td>
                      </tr> 
                      <?}
              }?>
          </tbody>
        </table>
      </div>
      <div class="col-xs-4">
        <table class="table table-bordered table-hover" border='1'>
          <thead>
            <tr> 
              <th> Marca </th>
              <th> Nº de veiculos</th>
              <th> Vida útil média</th>
              </tr>
          </thead>
          <tbody>
              <?if(count($this->list))
              {?>
                <?foreach($this->list as $vehicle2)
                  {?>
                      <tr>
                        <td><?=$vehicle2->vehicle_brand?></td>
                        <td><?=$vehicle2->vehicle_brand_num?></td>
                        <td><?=$vehicle2->life_cycle?></td>
                      </tr> 
                      <?}
              }?>
          </tbody>
        </table>
      </div>
    </div>  
  </div>  
</div>