<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li class="active"><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li>
        <li><a href="/grantee/vis"><i class="icon-picture"></i> Visualização </a></li>
      </ul>
    </div><!--/span-->
    <div class="span9">
    	<div class="page-header">
      	<h1>Pesquisa <small>gerencie aqui os dados do permissionário</small></h1>
      	<form class="form-search" action="/grantee/view" method="get">
      		<input type="text" class="input-xlarge search-query" placeholder="pesquisa" name="field" value="<?=$this->field?>">
          <select name="optionSearch">
            <option value="0">Pesquisar por:</option>
            <option value="1" <?if($this->optionSearch == 1) echo "selected='selected'"; ?>>Permissão</option>
            <option value="2" <?if($this->optionSearch == 2) echo "selected='selected'"; ?>>CPF</option>
            <option value="3" <?if($this->optionSearch == 3) echo "selected='selected'"; ?>>Nome</option>
          </select>
          <button type="submit" class="btn">Pesquisar</button>
      	</form>
      	<table class="table table-hover table-bordered">
      		<thead>
      			<th>Nome</th>
      			<th>Permissão</th>
      			<th>Início da Permissão</th>
            <th>Fim da Permissão</th>
      		</thead>
      		<tbody>
      			<?if(is_object($this->list) && !isset($this->list->name)){
      				foreach($this->list as $grantee){?>
		      			<tr>
		      				<td><a href="/grantee/edit/id/<?=$grantee->grantee_id?>"><?=$grantee->name?></a></td>
		      				<td><?=$grantee->permission?></td>
		      				<td><?=Application_Model_General::dateToBr($grantee->start_permission)?></td>
                  <td><?=Application_Model_General::dateToBr($grantee->end_permission)?></td>
		      			</tr>
      			<?} } else{?>
      				<tr>
      					<td colspan="7">Não encontrado nenhum permissionário na pesquisa.</td>
      				</tr>
      			<?}?>
      		</tbody>
      	</table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>
