<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li class="active"><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li><!-- 
        <li><a href="/grantee/vis"><i class="icon-picture"></i> Visualização </a></li> 
        <li><a href="#"><i class="icon-picture"></i> Emissão de Carteiras </a></li>
        <li><a href="#"><i class="icon-wrench"></i> Guias de Recolhimento </a></li> -->
      </ul>
    </div><!--/span-->
    <div class="span9">
    	<div class="page-header">
      	<h1>Pesquisa <small>gerencie aqui os dados do permissionário</small></h1>
      	<form class="form-search" action="/grantee/view" method="get">
      		<input type="text" class="input-xlarge search-query" placeholder="pesquisa" name="field" value="<?=$this->field?>">
          <select name="optionSearch">
            <option value="0">Pesquisar por:</option>
            <option value="1" <?if($this->optionSearch == 1) echo "selected='selected'"; ?>>Permissão</option>
            <option value="2" <?if($this->optionSearch == 2) echo "selected='selected'"; ?>>CPF</option>
            <option value="3" <?if($this->optionSearch == 3) echo "selected='selected'"; ?>>Nome</option>
          </select>
          <button type="submit" class="btn">Pesquisar</button>
      	</form>
      	<table class="table table-hover table-bordered">
      		<thead>
      			<th>Nome</th>
      			<th>Permissão</th>
      			<th>Início da Permissão</th>
            <th>Fim da Permissão</th>
      			<th>&nbsp;</th>
      		</thead>
      		<tbody>
      			<?if(is_object($this->list) && !isset($this->list->name)){
      				foreach($this->list as $grantee){?>
		      			<tr>
		      				<td><a href="/grantee/edit/id/<?=$grantee->grantee_id?>"><?=$grantee->name?></a></td>
		      				<td><?=$grantee->permission?></td>
		      				<td><?=Application_Model_General::dateToBr($grantee->start_permission)?></td>
                  <td><?=Application_Model_General::dateToBr($grantee->end_permission)?></td>
		      				<td><a href="/grantee/edit/id/<?=$grantee->grantee_id?>" class="editGrantee" data-toggle="tooltip" title="Editar permissionário"><i class="icon-pencil"></i></a></td>
		      				<td><a href="/grantee/print-data/id/<?=$grantee->grantee_id?>" class="printDataGrantee" data-toggle="tooltip" title="Imprimir dados"><i class="icon-file"></i></a></td>
                  <td><a href="#license_<?=$grantee->grantee_id?>" class="printLicenseGrantee" data-toggle="modal" title="Imprimir a carteira"><i class="icon-print"></i></a></td>
                  <td><a href="#" class="pendenciesGrantee" data-toggle="modal" title="Extrato de pendências"><i class="icon-book"></i></a></td>
                  <td><a href="#retire_<?=$grantee->grantee_id?>" class="retireGrantee" data-toggle="modal" title="Reserva"><i class="icon-flag"></i></a></td>
		      			</tr>
      			<?} } else{?>
      				<tr>
      					<td colspan="7">Não encontrado nenhum permissionário na pesquisa.</td>
      				</tr>
      			<?}?>
      		</tbody>
      	</table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>

<?if(is_object($this->list) && !isset($this->list->name)){
  foreach($this->list as $grantee){?>
<div id="retire_<?=$grantee->grantee_id?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Requerer Licença para Afastamento</h3>
  </div>
  <div class="modal-body">
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="initialDate">Data Inicial</label>
        <div class="controls">
          <input type="text" class="input-xlarge" id="initialDate" placeholder="data inicial" data-mask="99/99/9999">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="reason">Motivo</label>
        <div class="controls">
          <textarea class="input-xlarge" id="reason" placeholder="motivo" rows="5"></textarea>
        </div>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
    <button class="btn btn-primary">Salvar</button>
  </div>
</div>
<? } }?>

<?if(is_object($this->list) && !isset($this->list->name)){
  foreach($this->list as $grantee){?>
<div id="license_<?=$grantee->grantee_id?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Emissão de Carteira</h3>
  </div>
  <form class="form-horizontal" action="/grantee/print-license/id/<?=$grantee->grantee_id?>" method="post">
    <div class="modal-body">
        <div class="control-group">
          <label class="control-label" for="end_date">Data de Vencimento</label>
          <div class="controls">
            <input type="text" class="input-xlarge datepicker" id="end_date" name="end_date" placeholder="data de vencimento" data-mask="99/99/9999"  data-date="<?=date('d/m/Y')?>" data-date-format="dd/mm/yyyy">
          </div>
        </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
      <input type="submit" class="btn btn-primary" value="Salvar">
    </div>
  </form>
</div>
<? } }?>