<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="nav nav-list well">
        <li><a href="/grantee/new"><i class="icon-user"></i> Novo Permissionário </a></li>
        <li><a href="/grantee/view"><i class="icon-bullhorn"></i> Pesquisar Permissionário </a></li>
        <li><a href="/grantee/report"><i class="icon-map-marker"></i> Relatórios </a></li>
        <li class="active"><a href="/grantee/vis"><i class="icon-picture"></i> Visualização </a></li> 
      </ul>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
      	<h1>Visualização de Táxis</h1>
      </div>
      <div id="visTaxis"></div>
    </div>
  </div>
</div>