<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/inspection" class="list-group-item">
          <h4 class="list-group-item-heading">Fiscalização Rotineira</h4>
        </a>
        <a href="/inspection/new" class="list-group-item">Cadastro</a>
        <a href="/inspection/view" class="list-group-item">Pesquisa</a>
      </div>
      <div class="list-group">
        <a href="/clandestine" class="list-group-item">
          <h4 class="list-group-item-heading">Transporte Clandestino</h4>
        </a>
        <a href="/clandestine/new" class="list-group-item">Cadastro</a>
        <a href="/clandestine/view" class="list-group-item">Pesquisa</a>
      </div>
    </div><!--/span-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li class="active">Clandestino</li>
      </ol>
      <div class="well">
        <img class="img-responsive img-thumbnail" src="/img/fiscalizacao.jpg"><br><br>
        <h1>Fiscalização</h1>
        <p>Descrição de Fiscalização </p>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>