<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">Fiscalização Rotineira</li>
          <li><a href="/inspection/new">Cadastro</a></li>
          <li><a href="/inspection/view">Pesquisa</a></li>
          <li class="nav-header">Transporte Clandestino</li>
          <li class="active"><a href="/clandestine/new">Cadastro</a></li>
          <li><a href="/clandestine/view">Pesquisa</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
    	<div class="page-header">
      	<h1>Transporte Clandestino <small>dados do transporte clandestino</small></h1>
        <hr>
        <?=$this->form?>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>