<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/scheduling" class="list-group-item">
          <h4 class="list-group-item-heading">Agendamento</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos atendimentos</p>
        </a>
        <a href="/scheduling/treatment" class="list-group-item"><span class="glyphicon glyphicon-book"></span> Atendimentos</a>
        <a href="/scheduling/calendar" class="list-group-item"><span class="glyphicon glyphicon-calendar"></span> Recessos</a>
        <a href="/scheduling/hour" class="list-group-item"><span class="glyphicon glyphicon-saved"></span> Horários</a>
        <a href="/scheduling/report" class="list-group-item active"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
        <!-- <a href="/scheduling/graphic" class="list-group-item"><span class="glyphicon glyphicon-picture"></span> Gráfico</a> -->
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/scheduling">Agendamento</a></li>
        <li class="active">Relatórios</li>
      </ol>  
      <div class="page-header">
        <h1>Relatório <small>insira a data do relatório</small></h1>
        <hr>
        <form class="form-inline" action="/scheduling/report-scheduling" method="get" role="form">
          <div class="form-group col-md-3">
            <input type="text" class="form-control dateMask" placeholder="data inicial" name="start_date" value="<?=$this->field?>">
          </div>
          <div class="form-group col-md-3">
            <input type="text" class="form-control dateMask" placeholder="data final" name="end_date" value="<?=$this->field?>">
          </div>
          <button type="submit" class="btn btn-primary">Ok!</button>
         </form>
       </div>
    </div>
  </div>
</div>