
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <title>SETOP | Táxi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>
  <body style="text-align: center; color: #666;">

  	<h2>Relatório de Agendamento</h2>

		<table border="1" style="text-align: left;" align="center" cellpadding="3" cellspacing="3">
			<tr>
				<td><b>Nome</b></td>
				<td><b>E-mail</b></td>
				<td><b>Data</b></td>
				<td><b>Horário</b></td>
			</tr>
			<? foreach($this->data as $data){?>
			<tr>
				<td><?=$data->name?></td>
				<td><?=$data->email?></td>
				<td><?=Application_Model_General::dateToBr($data->date)?></td>
				<td><?=$data->hour?></td>
			</tr>
			<?}?>

		</table>

	</body>
</html>