
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Um sistema de gestão do transporte metropolitano">
    <meta name="author" content="SETOP">

    <title>SETOP | Ônibus Metropolitano</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/lib/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/lib/datepicker.css" rel="stylesheet">
    <link href="/css/scheduling.css" rel="stylesheet"> 

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/lib/html5shiv.js"></script>
      <script src="/js/lib/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

		<div class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">SETOP</a>
      </div>
    </div>

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
        <div class="page-header">
          <h1>Agendamento Online</h1>
        </div>
        <p class="lead">Escolha uma data e horário disponível e preencha os dados corretamente.</p>
      </div>

    <div class="container">
      <div class="row">
      	<div class="col-md-12">
			    <div id="calendar">
            <div></div>
          </div>
		  	</div>
	  	</div>
	  </div>
    </div>


	    

    <div id="footer">
      <div class="container">
        <p class="text-muted">Secretaria de Transportes e Obras Públicas - Superintendência de Transporte Metropolitano.</p>
      </div>
    </div>


    <script src="/js/lib/jquery-1.10.1.min.js" type="text/javascript"></script>
    <script src="/js/lib/jquery-ui.custom.min.js" type="text/javascript"></script>
    <script src="/js/lib/jquery.maskedinput.min.js" type="text/javascript"></script>
    <script src="/js/lib/bootstrap.min.js" type="text/javascript"></script>
    <script src="/js/lib/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="/js/schedule.js" type="text/javascript"></script>
  </body>
</html>
